-- ============================================================
-- CARGA INICIAL DO ACERVO
--
-- Os 680 videos que estavam no codigo, com as etiquetas
-- que ja tinham sido feitas na mao. Rode uma vez, depois de
-- aulas.sql. Rodar de novo nao duplica nada.
-- ============================================================

insert into public.aula (id, titulo, duracao, tipo, temas, posicoes, faixa) values
  ('yM71hoY84mw', '2 Ataques que mais funcionam contra oponentes mais pesados', 980, 'aula', '{geral}', '{}', null),
  ('dVdrfF6ORWw', 'Como pensar para DEFENDER O ARM LOCK', 273, 'aula', '{logica,finalizacao,defesa}', '{}', null),
  ('Xqc8pLe0-gI', 'Aprenda a pensar Jiu-Jitsu: entenda a lógica do controle da distância', 1624, 'aula', '{logica,controle,drill}', '{}', null),
  ('l0B-bA9N7Yk', 'Lógica do jiu jitsu - PARTE 13: a lógica da passagem flechando', 244, 'aula', '{logica,passagem}', '{}', null),
  ('Qykmb2t7qJ4', 'Como PENSAR na meia guarda - DIA 4 TIRANDO DÚVIDAS DE FAIXA AZUL', 1332, 'aula', '{logica,guarda,competicao}', '{meia_guarda}', 'azul'),
  ('krt0S4osKM8', 'Como PENSAR na guarda fechada - DIA 20 TIRANDO DÚVIDAS DE FAIXA BRANCA', 882, 'aula', '{logica,guarda,competicao}', '{guarda_fechada}', 'branca'),
  ('_6b-2auwrnM', 'Como se posicionar para pesar e limitar o oponente na 100kg - DIA 19 TIRANDO DÚVIDAS DE FAIXA BRANCA', 365, 'aula', '{controle,competicao}', '{cem_quilos}', 'branca'),
  ('KzVVTQhX7Hc', 'Como se comportar embaixo da 100kg - DIA 18 TIRANDO DÚVIDAS DE FAIXA BRANCA', 593, 'aula', '{logica,controle,competicao}', '{cem_quilos}', 'branca'),
  ('ggO8WwDX08s', 'A lógica da norte-sul - lógica do jiu jitsu parte 11', 233, 'aula', '{logica,controle}', '{norte_sul}', null),
  ('3ZfNChI5Kb4', 'DRILL DE RECONHECIMENTO - Onde seu corpo aprende o movimento e sua mente entende o momento.', 785, 'aula', '{logica,drill}', '{}', null),
  ('mLD0oD3PBHI', '5 Finalizações da Guarda Fechada (e a LÓGICA que faz elas pegarem)', 1323, 'aula', '{logica,finalizacao,guarda}', '{guarda_fechada}', null),
  ('0W4Z5zyOz-A', 'Como jogar guarda sem ser amassado - DIA 16 TIRANDO DÚVIDAS DE FAIXA BRANCA', 782, 'aula', '{guarda,competicao}', '{}', 'branca'),
  ('WLnsYkL-x9E', 'Como ser firme mesmo sendo o mais leve - DIA 15 TIRANDO DÚVIDAS DE FAIXA BRANCA', 549, 'aula', '{competicao}', '{}', 'branca'),
  ('knbV69KKEuE', 'Como raspar sendo leve e fraco - Dia 14 TIRANDO DÚVIDAS DE FAIXA BRANCA', 537, 'aula', '{raspagem,competicao}', '{}', 'branca'),
  ('sKgKAytEYlI', 'A lógica que conecta todas as guardas - Fundamentos de guarda', 1458, 'aula', '{logica,guarda}', '{}', null),
  ('xnDRb8KPRfg', 'O AJUSTE QUE FALTA NO SEU ARM LOCK - DIA 13 TIRANDO DÚVIDAS DE FAIXA BRANCA', 715, 'aula', '{finalizacao,competicao}', '{}', 'branca'),
  ('YD9IgcojPQY', 'Como se posicionar e quedar - DIA 12 TIRANDO DÚVIDAS DE FAIXA BRANCA', 690, 'aula', '{queda,competicao}', '{em_pe}', 'branca'),
  ('LPONY__hdhk', 'COMO PASSAR SEM SER RASPADO - DIA 11 TIRANDO DÚVIDAS DE FAIXA BRANCA', 974, 'aula', '{passagem,competicao}', '{}', 'branca'),
  ('RaMVmyuHhYE', 'Como transformar a posição que você treina em uma posição que funciona no rola - Jiu Jitsu', 873, 'aula', '{geral}', '{}', null),
  ('Jqo_N82KquM', 'Como finalizar sem machucar no jiu jitsu - DIA 10 TIRANDO DÚVIDAS DE FAIXA BRANCA', 808, 'aula', '{finalizacao,competicao}', '{}', 'branca'),
  ('0BFOb2f7k2I', 'COMO RESPIRAR E PENSAR NO CAOS DO ROLA - DIA 9 TIRANDO DÚVIDAS DE FAIXA BRANCA', 668, 'aula', '{logica,fisico,competicao}', '{}', 'branca'),
  ('NsPvArwIwBw', 'COMO PASSAR DE FORMA SEGURA - DIA 8 TIRANDO DÚVIDAS DE FAIXA BRANCA', 309, 'aula', '{passagem,competicao}', '{}', 'branca'),
  ('7BY4Zs1n_DI', 'SOBREVIVÊNCIA INTELIGENTE PARA JIU JITSU', 1914, 'aula', '{defesa}', '{}', null),
  ('F7NOIWabpN8', 'COMO ATACAR NA GUARDA FECHADA - DIA 7 TIRANDO DÚVIDAS DE FAIXA BRANCA', 1012, 'aula', '{guarda,competicao}', '{guarda_fechada}', 'branca'),
  ('Vkqum5w_yFE', 'COMO PENSAR NO ROLA MESMO SABENDO POUCAS POSIÇÕES -  DIA 6 TIRANDO DUVIDAS DE FAIXA BRANCA', 564, 'aula', '{logica,competicao}', '{}', 'branca'),
  ('p_s4xRJ2KvE', 'Introdução ao jiu-jitsu. O que é, como funciona a luta e quais os objetivos.', 1307, 'aula', '{logica,competicao}', '{}', null),
  ('0SSn7ahZKao', 'TIRANDO DÚVIDAS DE FAIXA BRANCA - DIA 5: O que fazer na guarda fechada?', 340, 'aula', '{guarda,competicao}', '{guarda_fechada}', 'branca'),
  ('x8U1ELU-c1s', 'TIRANDO DÚVIDAS DE FAIXA AZUL - DIA 3: O que fazer na meia guarda?', 538, 'aula', '{guarda,competicao}', '{meia_guarda}', 'azul'),
  ('Eq9GZN2adCk', 'TIRANDO DÚVIDAS DE FAIXA AZUL - DIA 2: O cara que cansa muito quando está por baixo', 486, 'aula', '{fisico,competicao}', '{}', 'azul'),
  ('BXdACdJoRYM', 'TIRANDO DÚVIDAS DE FAIXA BRANCA - DIA 4: como se posicionar na 100kg para dar pressão e dominar', 328, 'aula', '{logica,controle,competicao}', '{cem_quilos}', 'branca'),
  ('CttYs7JsTOI', 'COMO ESTUDAR JIU JITSU E EVOLUIR RÁPIDO.', 3266, 'aula', '{geral}', '{}', null),
  ('Ob3UpbX9Qnk', 'COMO DOMINAR MELHOR O OPONENTE QUE NATURALMENTE É MAIS FORTE QUE EU', 3577, 'aula', '{logica}', '{}', null),
  ('-H_vzPAnQqs', 'TIRANDO DÚVIDAS DE FAIXA BRANCA - DIA 3: como prender e dominar', 287, 'aula', '{logica,competicao}', '{}', 'branca'),
  ('y2NvVD1UXWk', 'TIRANDO DÚVIDAS DE FAIXA AZUL- DIA 1: Como manter uma 100kg', 348, 'aula', '{controle,competicao}', '{cem_quilos}', 'azul'),
  ('W-HzThF6mC4', 'TIRANDO DÚVIDAS DE FAIXA BRANCA - DIA 2: como se manter por cima e imobilizar.', 431, 'aula', '{controle,competicao}', '{}', 'branca'),
  ('BAr8sEnRzic', 'TIRANDO DÚVIDAS DE FAIXA BRANCA - DIA 1: O cara mais leve da academia.', 826, 'aula', '{competicao}', '{}', 'branca'),
  ('ovYyW5k7Myo', 'A pior crítica que eu já recebi no jiu-jítsu', 235, 'aula', '{geral}', '{}', null),
  ('Obe2RZAHxNw', 'A LÓGICA POR TRÁS DOS ATAQUES DIAGONAIS', 700, 'aula', '{logica}', '{}', null),
  ('arz5Zb5dIzk', 'POR ISSO O JIU JITSU É COMO UM XADREZ - Análise em câmera lente 3', 2238, 'aula', '{geral}', '{}', null),
  ('AmaT275uI9E', 'COMO NUNCA MAIS SER AMASSADO NO JIU JITSU - Guarda bola', 2194, 'aula', '{guarda}', '{}', null),
  ('BLY-Pk4hxZQ', 'O SISTEMA LÓGICO DA DEFESA NO JIU JITSU - A defesa acontece antes da finalização', 1789, 'aula', '{finalizacao,defesa}', '{}', null),
  ('UPyCCE_s3x0', 'Seu cérebro está sabotando seu jiu-jitsu- destrave em 30 minutos', 1784, 'aula', '{geral}', '{}', null),
  ('8bmwMS5FloE', 'A CIENCIA POR TRÁS DO SISTEMA OPERACIONAL DO JIU JITSU', 1886, 'aula', '{geral}', '{}', null),
  ('jswBGLBUpNA', 'O QUE É A PEGADA NO JIU JITSU, PORQUE FAZEMOS E COMO FAZER', 1189, 'aula', '{logica,controle}', '{}', null),
  ('hvFwwn64g70', 'A CIÊNCIA/LÓGICA POR TRÁS DA POSTURA NO JIU JITSU', 1571, 'aula', '{logica}', '{}', null),
  ('bg8BNTUW-Wg', 'APRENDA ISSO E SE TORNE INSUPORTÁVEL NO JIU JITSU', 1303, 'aula', '{geral}', '{}', null),
  ('eh8hsSD3QwM', '1 ANO DE CONHECIMENTO DE JIU JITSU EM 28 MINUTOS', 1690, 'aula', '{geral}', '{}', null),
  ('W7YPu6nPWDM', 'COMO SE COMPORTAR NA MEIA - POR BAIXO E POR CIMA', 1137, 'aula', '{logica}', '{}', null),
  ('k3uAxCW70Gg', 'O MAIOR HACK PARA COMPETIÇÃO DE JIU JITSU', 2334, 'aula', '{competicao}', '{}', null),
  ('4zBAoNj5I2Y', 'Treino para desenvolver um jiu jitsu inteligente - Parte 6', 924, 'aula', '{geral}', '{}', null),
  ('1pTi5qe2MYU', 'Quem é você no jiu jitsu?', 575, 'aula', '{geral}', '{}', null),
  ('ly32G9_Zjp4', 'Queda SUPER EFICAZ para faixa branca - SASAE', 171, 'aula', '{queda,competicao}', '{em_pe}', 'branca'),
  ('crudV4N6MtM', 'A lógica da passagem de guarda em primeira pessoa - POV JIU JITSU', 1671, 'aula', '{logica,passagem,guarda}', '{}', null),
  ('ECRMERoQxbc', 'A lógica do Jiu Jitsu quando você está jogando guarda em primeira pessoa', 591, 'aula', '{logica,guarda}', '{}', null),
  ('GUn5frjBbUI', 'Devo focar primeiro em jogar ou passar guarda?', 456, 'aula', '{passagem,guarda}', '{}', null),
  ('gHRlrLCSx0g', 'Como lutam os pesados ? - Análise em câmera lenta 4 - Roger Gracie X Xande Ribeiro', 1917, 'aula', '{competicao}', '{}', null),
  ('wR7Kabr3t3U', 'A LÓGICA DA FINALIZAÇÃO - Detalhes que farão você finalizar mais', 1060, 'aula', '{logica,finalizacao}', '{}', null),
  ('ULWeNfDD8A0', '3 formas de fazer o ARM LOCK - ESTUDANDO JIU JITSU 46', 315, 'aula', '{logica,finalizacao}', '{}', null),
  ('Hjt1gJxB39Q', 'DRILL de uma forma que você nunca viu', 1095, 'aula', '{drill}', '{}', null),
  ('LK25Rc38QyE', 'Como sair da MEDIOCRIDADE no JIU JITSU', 977, 'aula', '{defesa}', '{}', null),
  ('9OqtXhTCe04', 'Aprenda a treinar com esse vídeo', 1091, 'aula', '{geral}', '{}', null),
  ('8AmUT3-yGAc', 'Como começar o rola de joelhos? Qual a prioridade?', 1225, 'aula', '{geral}', '{}', null),
  ('outhHzRZtNU', 'Análise em câmera lenta 2 - Final do brasileiro 2024 mika vs jhonathan', 1585, 'aula', '{geral}', '{}', null),
  ('6PS_QnvcpJY', 'Analise em câmera lenta 1 - Rafael Mendes vs André Monteiro pan 2012', 2091, 'aula', '{geral}', '{}', null),
  ('ZcqJg5mXgDQ', 'A LÓGICA DA FINALIZAÇÃO o sistema lógico que você não percebe', 1873, 'aula', '{logica,finalizacao}', '{}', null),
  ('9G9Csa3r-s4', 'A melhor forma de entender e melhorar o jiu jitsu', 621, 'aula', '{logica}', '{}', null),
  ('Aq8-uQSegGM', 'Como criar ARMADILHAS no JIU Jitsu', 1446, 'aula', '{logica}', '{}', null),
  ('KEVCKVE9YqI', 'Entenda a ciência/lógica por trás do jiu jitsu e nunca mais seja o mesmo', 1431, 'aula', '{logica}', '{}', null),
  ('9nVlXAhvfHQ', 'A CIÊNCIA DA PRESSÃO NO JIU JITSU - Como distribuir seu peso', 1300, 'aula', '{controle}', '{}', null),
  ('UKqgsTCbPPg', 'O que separa um faixa azul comum de um faixa azul perigoso (5 pontos)', 768, 'aula', '{competicao}', '{}', 'azul'),
  ('XBoQcgSfnd0', 'Tudo que você precisa saber para nunca mais ficar perdido - Jiu jitsu para iniciantes', 3877, 'aula', '{geral}', '{}', null),
  ('bkJgnaliru0', 'Curso para faixa branca - TRANSIÇÕES E TIMING (Aula 5)', 2045, 'aula', '{drill,competicao}', '{}', 'branca'),
  ('wPkK7R_jWX8', 'Você pode PERDER a luta se NÃO souber DISSO.', 2206, 'aula', '{competicao}', '{em_pe}', null),
  ('W9lia5P0vzo', '- FORÇA + TÉCNICA / fundamentos do uso da força', 2941, 'aula', '{logica,fisico}', '{}', null),
  ('fcwn536J5mY', 'Curso para faixa branca- ATAQUES E DEFESAS (Aula 4)', 1385, 'aula', '{defesa,competicao}', '{}', 'branca'),
  ('nJtm72AAwmg', 'Curso para faixa branca - GUARDA E PASSAGEM  (Aula 3)', 1029, 'aula', '{passagem,guarda,competicao}', '{}', 'branca'),
  ('_Yx90I8ptvE', 'Curso para faixa branca - QUEDAS (Aula 2)', 1293, 'aula', '{queda,competicao}', '{em_pe}', 'branca'),
  ('0rbzOj15vdI', 'Curso para faixa branca - BASE (aula 1)', 1363, 'aula', '{competicao}', '{}', 'branca'),
  ('yfiqO1YYWo8', 'Como ganhar o primeiro grau no JIU JITSU', 333, 'aula', '{competicao}', '{}', null),
  ('NkGZTUyQ7rg', 'Os FUNDAMENTOS da guarda', 1275, 'aula', '{logica,guarda}', '{}', null),
  ('iuoPv1pGHaE', 'Aula completa de ataques da guarda fechada - Jiu Jitsu', 889, 'aula', '{guarda}', '{guarda_fechada}', null),
  ('oDaRQ2e6cbs', 'Como fazer uma mochila com seu kimono', 336, 'aula', '{geral}', '{}', null),
  ('hcW4TLjWzrk', 'Aula ZERO de jiu jitsu', 787, 'aula', '{geral}', '{}', null),
  ('-Rpi_ZXt8u4', 'Como rolar com uma mulher? - Entre as linhas do fundamento 03', 631, 'aula', '{logica}', '{}', null),
  ('1J3-tMmGK44', 'Engenheira têxtil ensina a forma CORRETA de cuidar do KIMONO.', 452, 'aula', '{geral}', '{}', null),
  ('kDfr3ja3qJY', 'Segure a 100kg sem ficar exausto - Estudando Jiu Jitsu 45', 922, 'aula', '{logica,controle}', '{cem_quilos}', null),
  ('mUKS0YvmGGU', 'Conheça os FUNDAMENTOS que estruturam o Jiu Jitsu', 806, 'aula', '{logica}', '{}', null),
  ('x7r8RdgU7k4', 'A raspagem que sempre funciona | Estudando Jiu Jitsu 43', 385, 'aula', '{logica,raspagem}', '{}', null),
  ('_--Vj9wjYQ8', 'A queda SUPER EFICAZ que você não conhece | Estudando Jiu JItsu 42', 339, 'aula', '{logica,queda}', '{em_pe}', null),
  ('Au7E31XY6Lc', 'Aula 41 - Como sair do 100kg | Estudando Jiu Jitsu', 976, 'aula', '{logica,defesa,controle}', '{cem_quilos}', null),
  ('fAOipa6yCQc', 'Você merece a próxima faixa?', 861, 'aula', '{competicao}', '{}', null),
  ('9jsBQzHn5io', 'Como se comportar na MONTADA - NeuroVLOG', 1443, 'aula', '{logica,controle}', '{montada}', null),
  ('2e0IaQK1dOs', 'Se tirar sua força o que sobra no teu Jiu Jitsu?', 1357, 'aula', '{fisico}', '{}', null),
  ('ku0KCngaRcA', 'Como parar de travar no rola  - Entre as linhas do Fundamento 01', 996, 'aula', '{logica,defesa}', '{}', null),
  ('UDDuQl88qX8', 'Como fazer um estrangulamento com a gola | Estudando Jiu Jitsu 40', 350, 'aula', '{logica,finalizacao}', '{}', null),
  ('OBdvYkuvopU', 'A raspagem sentada que você PRECISA saber | Estudando Jiu Jitsu 39', 354, 'aula', '{logica,raspagem}', '{}', null),
  ('KpOdRXy-Azw', 'Faixa azul esse vídeo é pra você!', 1097, 'aula', '{competicao}', '{}', 'azul'),
  ('2HWO5YZvcwM', 'O fundamento que muda tudo - Jiu Jitsu', 872, 'aula', '{logica}', '{}', null),
  ('ABM0KJi5i9g', 'Conheça os fundamentos que estruturam o JIu Jitsu.', 1182, 'aula', '{logica}', '{}', null),
  ('dSLq13vqyO8', 'Treino para desenvolver INTELIGÊNCIA DE LUTA no JIU JITSU - Parte 5', 400, 'aula', '{competicao}', '{}', null),
  ('CoaV7LorLrQ', 'Como fazer o TRIÂNGULO perfeito da guarda | Estudando Jiu Jitsu 38', 416, 'aula', '{logica,finalizacao,guarda}', '{}', null),
  ('uicgcaHcZIE', 'Treino para desenvolver INTELIGÊNCIA DE LUTA no JIU JITSU - parte 4', 792, 'aula', '{competicao}', '{}', null),
  ('LX-IfW5-u3M', 'Como se comportar na guarda - aula completa de jiu jitsu', 1379, 'aula', '{logica,guarda}', '{}', null),
  ('saT6LCMLjH4', 'Raspagem SUPER EFICIENTE da guarda laço | Estudando Jiu Jitsu 37', 252, 'aula', '{logica,raspagem,guarda}', '{guarda_aberta}', null),
  ('k1yFuFlmgL4', 'O conceito de progresso que está faltando no seu Jiu Jitsu', 436, 'aula', '{logica}', '{}', null),
  ('MeHSi71ZgMY', 'Por que tanta gente desiste do Jiu Jitsu?', 763, 'aula', '{logica}', '{}', null),
  ('HBSYibYdZHs', 'Qual a DISTÂNCIA certa no JIU JITSU? | Estudando Jiu Jitsu 36', 512, 'aula', '{logica,drill}', '{}', null),
  ('-llSAXRBtsA', 'A aula que você nunca teve mas deveria - aula completa de Jiu Jitsu', 1190, 'aula', '{geral}', '{}', null),
  ('sn_baSvWJQI', 'Você deveria estar fazendo essa passagem | Estudando Jiu Jitsu 35', 401, 'aula', '{logica,passagem}', '{}', null),
  ('u2SH_YOXX0g', 'Queda para BAIXOS | Estudando Jiu Jitsu 35', 622, 'aula', '{logica,queda}', '{em_pe}', null),
  ('HrEHDecSTZM', 'Manual completo de como chegar nas COSTAS | Estudando Jiu Jitsu 34', 573, 'aula', '{logica,controle}', '{costas}', null),
  ('v27DhrkcNdA', 'O treino que fará você ter INTELIGÊNCIA DE LUTA no jiu jitsu (parte 3)', 660, 'aula', '{competicao}', '{}', null),
  ('xn1dbIdSkZA', 'Treino para desenvolver INTELIGÊNCIA DE LUTA - Jiu Jitsu (parte 2)', 787, 'aula', '{competicao}', '{}', null),
  ('OzCQytWPius', 'Como ser um BOM PASSADOR  e matar qualquer guarda', 537, 'aula', '{guarda}', '{}', null),
  ('hMNNS7nRSt0', 'O vídeo que você precisa para se tornar um BOM GUARDEIRO', 452, 'aula', '{logica,guarda}', '{}', null),
  ('-2eNxP1x550', 'Você deveria desistir do jiu jitsu', 1110, 'aula', '{geral}', '{}', null),
  ('alXQx1HDQ18', 'Você deveria usar a faixa no rola | Estudando Jiu Jitsu 33', 683, 'aula', '{logica,competicao}', '{}', null),
  ('5fOLrZ7nuzQ', 'Tudo e nada 02- conceitos necessários, equilíbrio, quedas, consciência de luta e outras coisas', 730, 'aula', '{logica,queda,fisico,competicao}', '{em_pe}', null),
  ('uJGcNEG5OuA', 'ARM LOCK - como defender | Estudando Jiu Jitsu 32', 390, 'aula', '{logica,finalizacao,defesa}', '{}', null),
  ('tkUyXOnCROc', 'Tudo e nada 01 - Não querer ganhar, pegadas, essência, neurojitsu e outras coisas.', 1083, 'aula', '{controle}', '{}', null),
  ('dJk_fHf8n00', 'TRIÂNGULO - como sair | Estudando Jiu Jitsu 31', 455, 'aula', '{logica,finalizacao}', '{}', null),
  ('7eiYOZVlfXI', 'TARIKOPLATA - como fazer  | Estudando Jiu Jitsu 30', 500, 'aula', '{logica}', '{}', null),
  ('2lJyHkCBpbI', 'Treino para desenvolver INTELIGÊNCIA DE LUTA / método Neurojitsu', 578, 'aula', '{competicao}', '{}', null),
  ('JC9zssc06j0', 'Nunca te contaram isso sobre o JIU JITSU', 1595, 'aula', '{geral}', '{}', null),
  ('qYCc3zcbh6M', 'Analisando lutas dos inscritos 01 - Júlio na meia', 960, 'aula', '{competicao}', '{}', null),
  ('0u1KgyiB0Gs', 'QUEDA para quem é ALTO | Estudando Jiu Jitsu 29', 563, 'aula', '{logica,queda}', '{em_pe}', null),
  ('9icNg4fWWcg', 'Aula completa de Jiu Jitsu para iniciantes', 3237, 'aula', '{geral}', '{}', null),
  ('Rmlx8CkK-yM', '3 ANIMES que todo JIUJITEIRO precisa assistir', 454, 'aula', '{geral}', '{}', null),
  ('-fprol2S5c0', 'Chave de panturrilha | Estudando Jiu Jitsu 28', 451, 'aula', '{logica,finalizacao}', '{}', null),
  ('-MUTZzL0qwc', 'O jeito certo de SAIR O QUADRIL | Estudando Jiu Jitsu 27', 299, 'aula', '{logica,fisico}', '{}', null),
  ('rkp9JrckBE8', 'Estou sendo AMASSADO e agora? | Estudando Jiu Jitsu 26', 355, 'aula', '{logica}', '{}', null),
  ('IyM9g828J_k', 'Aula completa de Jiu Jitsu - Desequilíbrio por Gabriel Neuro Jitsu', 3887, 'aula', '{queda,fisico}', '{}', null),
  ('E3FQek_Va4s', 'Estrangulamento SURPRESA | Estudando Jiu Jitsu 25', 201, 'aula', '{logica,finalizacao}', '{}', null),
  ('3adTkneSSsM', 'Como prever o próximo passo do oponente no JIU JITSU | Estudando Jiu Jitsu 24', 487, 'aula', '{logica}', '{}', null),
  ('P_4LMW9_I1c', 'Como fazer OMOPLATA na guarda | Estudando Jiu Jitsu 23', 493, 'aula', '{logica,finalizacao,guarda}', '{}', null),
  ('AFmdCqCVOBU', 'Triângulo saindo das costas | Estudando Jiu Jitsu 22', 370, 'aula', '{logica,finalizacao,controle}', '{costas}', null),
  ('9yfsu67OQhw', 'Estudando Jiu Jitsu - arm lock / triângulo / omoplata (parte 2)', 537, 'aula', '{logica,finalizacao}', '{}', null),
  ('H4tlCY0RIpo', 'A finalização que todo mundo pode fazer mas ninguém faz | Estudando Jiu Jitsu 21', 436, 'aula', '{logica,finalizacao}', '{}', null),
  ('adBmFb_qido', 'Como passar BANDEJANDO | Estudando Jiu Jitsu 20', 435, 'aula', '{logica,passagem}', '{}', null),
  ('D4fBKc0bUzo', 'Como raspar quando o PASSADOR SOBE na guarda fechada? | Estudando Jiu Jitsu 19', 431, 'aula', '{logica,raspagem,guarda}', '{guarda_fechada}', null),
  ('kGvWSZ60evc', 'Como criar ESTRATÉGIA no JIU JITSU?', 561, 'aula', '{logica}', '{}', null),
  ('Gbrai-Rd1gI', 'Como descobrir se você é GUARDEIRO ou PASSADOR?', 617, 'aula', '{guarda}', '{}', null),
  ('w7dby-HDD5g', 'Como SAIR da 50/50 | Estudando Jiu Jitsu 18', 284, 'aula', '{logica,defesa}', '{perna}', null),
  ('JYE9mOluItE', 'Como ESCAPAR da GUARDA ARANHA 🕷️ | Estudando Jiu Jitsu 17', 418, 'aula', '{logica,defesa,guarda}', '{guarda_aberta}', null),
  ('HT11mkfL-Js', 'Estudando GUARDA LAÇO | Estudando Jiu Jitsu 16', 620, 'aula', '{logica,guarda}', '{guarda_aberta}', null),
  ('1x-HzzBn1oc', 'Como DEFENDER a BOTINHA/ chave de pé | Estudando Jiu Jitsu 15', 311, 'aula', '{logica,finalizacao,defesa}', '{em_pe,perna}', null),
  ('00Z8B0MuFqI', 'Como DEFENDER o ESTRANGULAMENTO X | Estudando Jiu Jitsu 14', 296, 'aula', '{logica,finalizacao,defesa}', '{}', null),
  ('gx401p_Dvs0', 'Estudando leg lock  chave de joelho | Estudando Jiu Jitsu 13', 400, 'aula', '{logica,finalizacao}', '{perna}', null),
  ('Mnu4Ofju6Uc', 'Estudando MÃO DE VACA / Estudando Jiu Jitsu 12', 1164, 'aula', '{logica}', '{}', null),
  ('E_nUSvh_KKc', 'Estudando GUARDA FECHADA / Estudando Jiu Jitsu 11', 506, 'aula', '{logica,guarda}', '{guarda_fechada}', null),
  ('E4Cbr4o_bjo', 'Estudando TRIÂNGULO / Estudando Jiu Jitsu 10', 594, 'aula', '{logica,finalizacao}', '{}', null),
  ('cjZwsS7jqZs', 'Como treinar JIU JITSU SOZINHO?', 480, 'aula', '{geral}', '{}', null),
  ('RQ-ucsrq1m4', 'Estudando ARM LOCK / Estudando Jiu Jitsu 08', 516, 'aula', '{logica,finalizacao}', '{}', null),
  ('Ix7Km8XmW0k', 'Como PASSAR quando o guardeiro está SENTADO? / Estudando Jiu Jitsu 09', 477, 'aula', '{logica,passagem,guarda}', '{}', null),
  ('T4M_8n-RBJQ', 'BOTINHA ou CHAVE DE PÉ reta / Estudando Jiu Jitsu 07', 343, 'aula', '{logica,finalizacao}', '{em_pe,perna}', null),
  ('DVe5PBAVIV0', 'Qual melhor QUEDA para faixa branca? / judo - jiu jitsu', 371, 'aula', '{queda,competicao}', '{em_pe}', 'branca'),
  ('5WhhpYQygec', 'Como se comportar no tatame? / Jiu jitsu - Judô', 575, 'aula', '{logica,queda}', '{}', null),
  ('vOpB9N5wmpk', 'JUDÔ X JIU JITSU | Qual a diferença?', 138, 'aula', '{queda}', '{}', null),
  ('ORHBUwPg794', 'Como lutar com alguém mais PESADO / JIU JITSU', 231, 'aula', '{competicao}', '{}', null),
  ('yq91sVtGiL0', 'KIMONO de qual COR? Por que algumas academias exigem o branco?', 377, 'aula', '{logica}', '{}', null),
  ('JSCEZeCNHwc', '3 ESTRANGULAMENTOS NAS COSTAS / Estudando Jiu Jitsu 06', 606, 'aula', '{logica,finalizacao,controle}', '{costas}', null),
  ('L5Q9J8pZbjk', 'DRILL / MOBILIDADE para GUARDEIROS - jiu jitsu', 328, 'aula', '{guarda,fisico,drill}', '{}', null),
  ('giNhtfjOJJk', 'Como pegar as COSTAS no JIU JITSU / Estudando Jiu Jitsu 05', 756, 'aula', '{logica,controle}', '{costas}', null),
  ('oXXHRtsz72s', 'DRILL/ MOBILIDADE para quem tem até 1 ano de JIU JITSU', 352, 'aula', '{fisico,drill}', '{}', null),
  ('tHDSibOffr4', 'SAÍDA DA MONTADA - ESTUDANDO JIU JITSU 04', 379, 'aula', '{logica,controle}', '{montada}', null),
  ('qCDcYqn2a6g', 'Como saber o que fazer no rola / entenda o próximo passo', 299, 'aula', '{logica}', '{}', null),
  ('V36_R8mDUA8', 'Como deixar de ser INICIANTE no JIU JITSU', 1167, 'aula', '{geral}', '{}', null),
  ('WuGL3giC46Q', 'SAINDO DA NORTE-SUL / ESTUDANDO JIU JITSU - 03', 351, 'aula', '{logica,controle}', '{norte_sul}', null),
  ('B_r6zoNp8sE', '3 SAÍDAS DA 100kg / estudando jiu jitsu 02', 852, 'aula', '{logica,controle}', '{cem_quilos}', null),
  ('ROS_HgQ5cuc', 'Como amarrar a faixa / vestir o kimono', 177, 'aula', '{competicao}', '{}', null),
  ('6zJyOZzncjc', 'Como escolher onde treinar JIU-JÍTSU?', 256, 'aula', '{geral}', '{}', null),
  ('18r4F7PuM_4', 'Por que praticar uma arte marcial/luta?', 725, 'aula', '{logica,competicao}', '{}', null),
  ('MaxXgxKc_3M', 'Neurojitsu', 608, 'aula', '{geral}', '{}', null),
  ('Fb3GwaR8K7M', 'Estudando jiu-jítsu / arm lock / triângulo / omoplata', 975, 'aula', '{logica,finalizacao}', '{}', null),
  ('kxgQmaK-oN8', 'A primeira aula de JIU JITSU que você NÃO teve', 1039, 'aula', '{geral}', '{}', null),
  ('vcSOI9vgcQE', 'Como funcionam as GRADUAÇÕES no JIU JITSU? - história, ordem e opniões do mestre Enock.', 358, 'aula', '{logica}', '{}', null),
  ('foOCjCP0iMc', 'Passagem de meia guarda - NeuroJitsu', 215, 'aula', '{passagem,guarda}', '{meia_guarda}', null),
  ('KqRXqyiOAyM', 'Inteligência Marcial', 401, 'aula', '{geral}', '{}', null),
  ('o5yHGJc5UVo', 'Como PENSAR e se COMPORTAR na meia guarda', 175, 'short', '{logica,guarda}', '{meia_guarda}', null),
  ('5TvTGKxITN4', 'Como sair do básico no jiu jitsu #bjj', 65, 'short', '{defesa}', '{}', null),
  ('AGEQ9dyP4J4', 'Game do jiu jitsu #bjj #jiujitsu', 173, 'short', '{geral}', '{}', null),
  ('LfHCmF6ntLI', 'Como controlar a meia guarda #bjj', 176, 'short', '{controle,guarda}', '{meia_guarda}', null),
  ('x6rUwSGHVMY', 'Como sair da 100kg #bjj #jiujitsu', 179, 'short', '{defesa,controle}', '{cem_quilos}', null),
  ('sYIoLE9nfcg', 'A lógica da finalização de ombro', 139, 'short', '{logica,finalizacao}', '{}', null),
  ('2oYVavj_Fcw', 'A lógica da raspagem - lógica do jiu jitsu parte 14', 167, 'short', '{logica,raspagem}', '{}', null),
  ('VTjzrinh-Js', 'Como se comportar na meia guarda? #bjj #jiujitsu', 179, 'short', '{logica,guarda}', '{meia_guarda}', null),
  ('jdsQG-92b_M', 'Como fazer arm lock na guarda #bjj #jiujitsu', 157, 'short', '{finalizacao,guarda}', '{}', null),
  ('uiv_XnUivrI', 'Como pensar na meia guarda? #bjj #jiujitsu #bjjgirl', 172, 'short', '{logica,guarda}', '{meia_guarda}', null),
  ('mYc-JF1KNGQ', 'Como finalizar na guarda fechada? #bjj #jiujitsu', 170, 'short', '{finalizacao,guarda}', '{guarda_fechada}', null),
  ('onMqSTYaAUw', 'Por isso você apanha cada dia mais no jiu jitsu', 100, 'short', '{geral}', '{}', null),
  ('wcVlYUklQOM', 'O que fazer na guarda fechada? #bjj #jiujitsu', 170, 'short', '{guarda}', '{guarda_fechada}', null),
  ('727seJqo0m8', 'Como se posicionar na 100kg #bjj #jiujitsu', 169, 'short', '{controle}', '{cem_quilos}', null),
  ('f88V688J4u0', 'A logica do jiu jitsu - PARTE 11: A lógica da raspagem tesourinha #bjj #jiujitsu #bjjgirls', 175, 'short', '{logica,raspagem}', '{}', null),
  ('Juz7EsDDE_M', 'Como sair de baixo na 100kg #bjj #jiujitsu', 174, 'short', '{defesa,controle}', '{cem_quilos}', null),
  ('fcUPXzPyctY', 'Como se comportar na 100kg #bjj', 180, 'short', '{logica,controle}', '{cem_quilos}', null),
  ('CAY5vTtf2Co', 'A lógica do arm lock #bjj', 166, 'short', '{logica,finalizacao}', '{}', null),
  ('AO5STuSVVpk', 'A lógica do jiu-jítsu parte 12 a lógica do domínio das costas #jiujitsu #bjj #bjjgirls #neurojitsu', 173, 'short', '{logica,controle}', '{costas}', null),
  ('uVE1eBra0UM', 'Como se comportar na guarda laço - DIA 17 TIRANDO DÚVIDAS DE FAIXA BRANCA', 146, 'short', '{logica,guarda,competicao}', '{guarda_aberta}', 'branca'),
  ('qMr-tps8s70', 'Como raspar na guarda laço #bjj', 127, 'short', '{raspagem,guarda}', '{guarda_aberta}', null),
  ('eBKQiwTC5WI', 'Jiu-Jitsu: Leia a Luta e Domine Cada Intenção! #shorts', 43, 'short', '{competicao}', '{}', null),
  ('beJhcyg5uZ8', 'Jiu-Jitsu: Repetição é a Chave para Excelência', 46, 'short', '{drill}', '{}', null),
  ('JpDvjoQyUS4', 'Jiu-jítsu em sua essência #jiujitsu #bjjgirls #bjj', 175, 'short', '{geral}', '{}', null),
  ('Ri5MQJjpkhQ', 'Específico de guarda de lá riva. passou volta, raspou volta, muita técnica envolvida #JiuJitsu #BJJ', 90, 'short', '{guarda}', '{guarda_aberta}', null),
  ('nxiPEvtaUZg', 'A Lógica do Jiu-Jitsu , EP. 10: A Lógica da Montada #JiuJitsu #BJJ #BJJGirl #BrazilianJiuJitsu', 178, 'short', '{logica,controle}', '{montada}', null),
  ('1jS07aFvVyo', 'O segredo da defesa no jiu jitsu', 115, 'short', '{defesa}', '{}', null),
  ('dqW7XXF_MvE', 'Destrua Pegadas de Jiu-Jitsu', 116, 'short', '{controle}', '{}', null),
  ('VDmF6tbUTzo', 'Jiu-Jitsu: Use Seu Corpo Inteiro Para Vencer! #shorts', 73, 'short', '{geral}', '{}', null),
  ('zyv65wu0GyM', 'Finalizações da guarda fechada #bjj', 131, 'short', '{finalizacao,guarda}', '{guarda_fechada}', null),
  ('leSV6nSWsA4', 'Tatame para treinar em casa', 60, 'short', '{geral}', '{}', null),
  ('UmzHn1Udkzk', 'A lógica da 100kg no jiu jitsu', 179, 'short', '{logica,controle}', '{cem_quilos}', null),
  ('tmOphqi2eN8', 'Guarda Fechada para Raspagem: Domine o Controle Total! #shorts', 80, 'short', '{raspagem,controle,guarda}', '{guarda_fechada}', null),
  ('fzVocrG3IYY', 'Seja agressivo no rola! #bjj #jiujitsu', 30, 'short', '{geral}', '{}', null),
  ('5vP_6vP6YYY', 'Como jogar guarda #jiujitsu', 135, 'short', '{guarda}', '{}', null),
  ('1JuaNSf4tfU', 'Como jogar guarda sem ser amassado', 174, 'short', '{guarda}', '{}', null),
  ('3Ca3OyLFtRQ', '#bjj #jiujitsu', 105, 'short', '{geral}', '{}', null),
  ('0HdBviP21NI', 'Como pensar para passar guarda? Qual a lógica desse momento? #bjj #jiujitsu #bjjgirl', 166, 'short', '{logica,passagem,guarda}', '{}', null),
  ('H9bH-UTw7Bc', 'Como pesar mesmo sendo leve #bjj', 180, 'short', '{geral}', '{}', null),
  ('t6jD93WwHws', 'Como jogar guarda quando o rola começa de joelhos  #bjj', 68, 'short', '{guarda}', '{}', null),
  ('e8X4ju8ZvVc', 'Como passar sendo muito leve #bjj', 174, 'short', '{passagem}', '{}', null),
  ('nDf7dRVbfQQ', 'Seja agressivamente elegante', 92, 'short', '{geral}', '{}', null),
  ('9oFQ8OK9OA8', 'Como iniciar o rola de joelhos', 150, 'short', '{geral}', '{}', null),
  ('28g8VkPEJsI', 'Como respirar no rola', 94, 'short', '{fisico}', '{}', null),
  ('4Xms9fitohk', 'Como raspar?', 174, 'short', '{raspagem}', '{}', null),
  ('c3ooB1hlQE0', 'Como cair?', 148, 'short', '{geral}', '{}', null),
  ('wcAtIsAR6OM', 'A lógica do jiu jitsu - parte 3: Como finalizar na luta em pé', 126, 'short', '{logica,finalizacao,competicao}', '{em_pe}', null),
  ('HTNq1dq92Wo', 'Faz sentido? Link tá na bio! #bjj #jiujitsu', 97, 'short', '{geral}', '{}', null),
  ('RuSlLb6TGOE', 'A lógica do jiu jitsu - parte 2: Como chamar para guarda em segurança', 79, 'short', '{logica,guarda}', '{}', null),
  ('1jxoh1h4n-I', 'Como finalizar lutando em pé no jiu jitsu', 126, 'short', '{finalizacao,competicao}', '{em_pe}', null),
  ('SAjXloVgVZk', 'como pensar jogando guarda no jiu jitsu', 150, 'short', '{logica,guarda}', '{}', null),
  ('CcXaVEZao-s', 'Como chamar para guarda em pé? #bjj #jiujitsu #bjjgirl', 79, 'short', '{guarda}', '{em_pe}', null),
  ('fDZRztT2e_4', 'Como dominar no jiu jitsu', 119, 'short', '{logica}', '{}', null),
  ('t8hstU33nGc', 'O que fazer quando pegam suas costas no jiu jitsu', 124, 'short', '{controle}', '{costas}', null),
  ('hOGdLyIAo1E', 'A lógica do arm drag no jiu jitsu', 121, 'short', '{logica}', '{}', null),
  ('E5ADvINkbpc', 'A lógica do jiu jitsu parte 1- Como lutar em pé', 164, 'short', '{logica,competicao}', '{em_pe}', null),
  ('AqyHCVSg-2E', 'A lógica do jiu jitsu - parte 1 #bjj #jiujitsu #bjjgirls', 164, 'short', '{logica}', '{}', null),
  ('-6S-QDbH8Lk', 'Jiu jitsu em pé', 12, 'short', '{geral}', '{em_pe}', null),
  ('e3ePTdySCn4', 'Força excessiva no jiu jitsu #bjj', 65, 'short', '{fisico}', '{}', null),
  ('VPCBL313EEU', 'O ajuste que falta no seu arm lock #bjj #jiujitsu', 177, 'short', '{finalizacao}', '{}', null),
  ('xCEvLlwL6Ps', 'Como tirar a estrutura do oponente no jiu jitsu', 138, 'short', '{logica}', '{}', null),
  ('SYLVEhBVSQ0', 'A lógica do triângulo #bjj #jiujitsu', 81, 'short', '{logica,finalizacao}', '{}', null),
  ('3I_cOn_a814', 'Qual sua intenção no rola? #bjj #jiujitsu', 54, 'short', '{geral}', '{}', null),
  ('kPXPk4jY_6I', 'Como pensar na hora do rola no jiu jitsu', 163, 'short', '{logica}', '{}', null),
  ('4qVFaeQdPz4', 'situações de domínio no jiu jitsu', 88, 'short', '{geral}', '{}', null),
  ('_XHc9Vs2Ce8', 'Video completo aqui no canal', 180, 'short', '{geral}', '{}', null),
  ('-_Bj79xQEv8', 'Alavancas no jiu jitsu #bjj #jiujitsu', 96, 'short', '{geral}', '{}', null),
  ('mQKH13J8ONM', 'Como se comportar nas costas no jiu jitsu', 81, 'short', '{logica,controle}', '{costas}', null),
  ('wTq1fNsjls0', 'Não resista no rola!', 70, 'short', '{geral}', '{}', null),
  ('02dqZbBbK9A', 'Use 17 mãos no jiu jitsu', 162, 'short', '{geral}', '{}', null),
  ('UzuF37oK9zE', 'Como lutar em pé no JIU JITSU', 176, 'short', '{competicao}', '{em_pe}', null),
  ('INFivqiz1iA', 'Mobilidade para jiujitsu  #bjj #jiujitsu', 18, 'short', '{fisico}', '{}', null),
  ('TkjTWJHVbhQ', 'Como fazer omoplata na guarda fechada #bjj #jiujitsu', 64, 'short', '{finalizacao,guarda}', '{guarda_fechada}', null),
  ('eJJ1BzmMfJg', 'Como começar o rola de joelhos #bjj #jiujitsubrasiloficial', 103, 'short', '{geral}', '{}', null),
  ('phg3hI61yWc', 'Como controlar o adversário #bjj #jiujitsu', 65, 'short', '{controle}', '{}', null),
  ('6D27ekkZEdI', 'Raspagem da fechada #bjj #jiujitsu', 6, 'short', '{raspagem}', '{}', null),
  ('-IWU74Xko4k', 'Como passar mesmo quando te empurram #bjj #jiujitsu', 179, 'short', '{passagem}', '{}', null),
  ('YdHwp65DPvY', 'Sim ou não? #bjj #jiujitsu', 78, 'short', '{geral}', '{}', null),
  ('q8o9kSottI0', 'O katagatame que apaga #bjj #jiujitsu', 157, 'short', '{finalizacao}', '{}', null),
  ('5PEQI51m5T4', 'Quiz do BJJ #bjj #jiujitsu', 37, 'short', '{geral}', '{}', null),
  ('si3rRgn5UzQ', 'Vídeo completo aqui no canal #bjj #jiujitsu #bjjgirl', 180, 'short', '{geral}', '{}', null),
  ('j1e3a-feAdA', 'O desequilíbrio é a chave do sucesso', 66, 'short', '{queda,fisico}', '{}', null),
  ('H9GHwq-72eE', 'Como se defender no jiu jitsu #bjj #jiujitsu', 176, 'short', '{defesa}', '{}', null),
  ('Hin99UG1ddI', 'Pode lavar a faixa? #bjj #jiujitsu', 24, 'short', '{competicao}', '{}', null),
  ('vCB41kyy0zk', 'Como respirar no rola #jiujitsu #bjj', 170, 'short', '{fisico}', '{}', null),
  ('Y-SCPTxipo8', 'POV: você é jiujiteiro', 44, 'short', '{geral}', '{}', null),
  ('DZijM_Vtwuk', 'Como finalizar na guarda fechada #bjj #jiujitsu', 145, 'short', '{finalizacao,guarda}', '{guarda_fechada}', null),
  ('b4JNA-RFHh8', 'Como raspar da guarda fechada #bjj #jiujitsu', 156, 'short', '{raspagem,guarda}', '{guarda_fechada}', null),
  ('jzhBw_pCIrg', 'Como trocar pegadas no jiu jitsu', 101, 'short', '{controle}', '{}', null),
  ('5EDJ2f0KscE', 'O que fazer quando tiver jogando guarda? #bjj #jiujitsu', 171, 'short', '{guarda}', '{}', null),
  ('2XLAnzySG1g', 'Como pensar no rola sabendo poucas posições #bjj', 171, 'short', '{logica}', '{}', null),
  ('_p4JKGa9spE', 'Como pensar na hora do rola', 40, 'short', '{logica}', '{}', null),
  ('-4_gEki9gSM', 'O que fazer na montada', 42, 'short', '{controle}', '{montada}', null),
  ('4nPLW1H8DvQ', 'O que fazer na guarda fechada? #bjj #jiujitsu #guardafechada', 179, 'short', '{guarda}', '{guarda_fechada}', null),
  ('KDX2bpOErQY', 'O que fazer na guarda fechada? #bjj #jiujitsu', 179, 'short', '{guarda}', '{guarda_fechada}', null),
  ('Sf8lDPSEwlg', 'O que fazer na meia guarda profunda? #bjj #jiujitsu', 179, 'short', '{guarda}', '{meia_guarda}', null),
  ('MCgGkeMlh2E', 'Use seu corpo como uma mão no jiu jitsu', 65, 'short', '{geral}', '{}', null),
  ('n_lO8oRH1D4', 'Saia do automático no jiu jitsu', 76, 'short', '{geral}', '{}', null),
  ('7xmdGfkM1jY', 'Como sair da 100kg? #bjj #jiujitsu', 178, 'short', '{defesa,controle}', '{cem_quilos}', null),
  ('bTatov57tj0', 'Como jogar por baixo sem cansar #bjj #jiujitsu', 178, 'short', '{fisico}', '{}', null),
  ('dSX-eVGXRJU', 'Quebre a postura e passe a guarda #bjj #jiujitsu', 56, 'short', '{guarda}', '{}', null),
  ('ugbsLRYNcc0', 'Como estourar pegada #bjj', 64, 'short', '{controle}', '{}', null),
  ('ljVaKbNv25I', 'Dia 9 tirando dúvidas de faixa branca #bjj #jiujitsu', 175, 'short', '{competicao}', '{}', 'branca'),
  ('rIsskw7kXFY', 'Saia do automático no jiu jitsu', 76, 'short', '{geral}', '{}', null),
  ('iqFpmXxXUaE', 'O treino não é para vencer', 36, 'short', '{geral}', '{}', null),
  ('gJdjb31pjvI', 'Estudando meia guarda #bjj #jiujitsu', 81, 'short', '{guarda}', '{meia_guarda}', null),
  ('EGp_a84LBC8', 'Aumente seu gás entendendo a fisiologia da respiração aula 2 - link na bio #bjj #bjjgirls #jiujitsu', 142, 'short', '{logica,fisico}', '{}', null),
  ('X8Cc5_5zGE8', 'Pior crítica do jiu-jítsu #bjj #jiujitsu', 177, 'short', '{geral}', '{}', null),
  ('hFl46Y8qu3s', 'Aula completa de estrutura na plataforma Neurojitsu. Aula 20 do mapa do jiu-jítsu #bjj #jiujitsu', 143, 'short', '{logica}', '{}', null),
  ('TLNmri4DoC8', 'Caro pra quem? Link na bio #bjj #jiujitsu', 19, 'short', '{geral}', '{}', null),
  ('X73wo3GZKgs', 'Passagem de meia em primeira pessoa 👀 #bjj #jiujitsu', 74, 'short', '{passagem}', '{}', null),
  ('_cmxG0KKI5g', 'Tirando dúvidas de faixa branca - dia 3 #bjj #jiujitsu', 170, 'short', '{competicao}', '{}', 'branca'),
  ('sPu87EwOEQ0', 'Oss #bjj #jiujitsu', 120, 'short', '{geral}', '{}', null),
  ('AyB4PetX4Uk', 'Seu cérebro está atrapalhando seu jiu jitsu', 179, 'short', '{geral}', '{}', null),
  ('FsoR28rfqZU', 'Como sair da 100kg', 180, 'short', '{defesa,controle}', '{cem_quilos}', null),
  ('bF76MwCV9VA', 'Como colocar esparadrapo no dedo #bjj #jiujitsu', 164, 'short', '{geral}', '{}', null),
  ('8g-Wynl0Z2A', 'Como se comportar na meia guarda #bjj', 173, 'short', '{logica,guarda}', '{meia_guarda}', null),
  ('3ViyVucESSI', 'Pese como um elefante', 176, 'short', '{geral}', '{}', null),
  ('AmCW7mHjDKo', 'Treinar mais garante evoluir mais? #bjj', 133, 'short', '{geral}', '{}', null),
  ('89roQYAVrkw', 'A lógica do estrangulamento #bjj #jiujitsu #bjjgirls', 124, 'short', '{logica,finalizacao}', '{}', null),
  ('3MXZYsMx1yo', 'Como passar na meia sem dar as costas #jiujitsu #bjj', 180, 'short', '{passagem,controle}', '{costas}', null),
  ('ETlU9zk8p3U', 'Passagem de mais guarda quebrando a estrutura do nosso adversário #bjj #jiujitsu', 80, 'short', '{logica,passagem,guarda}', '{}', null),
  ('4_GCBhdm5Sc', 'Abriu a mente aí? Manda pra seu amigo FB #bjj #jiujitsu', 149, 'short', '{geral}', '{}', null),
  ('LfUz73NYQ4o', 'Por que não lembro as posições? #bjj #jiujitsu', 60, 'short', '{logica}', '{}', null),
  ('JShVlAEhsQ4', 'Dia 1 ajudando faixa branca  #jiujitsu  #bjj #fundamentosdojiujitsu', 165, 'short', '{logica,competicao}', '{}', 'branca'),
  ('tdKt_X4RhNM', 'Como treinar melhor o jiu-jítsu #bjj #jiujitsu', 118, 'short', '{geral}', '{}', null),
  ('BA8c4DeTtJg', 'Sem postura você tira sua própria força #bjj #jiujitsu', 46, 'short', '{fisico}', '{}', null),
  ('P3VsW8nKAnI', '#bjj #jiujitsu', 25, 'short', '{geral}', '{}', null),
  ('0j1-zBupJZw', 'Como quebrar postura na guarda. Gostou da dica? Oss! #bjj #jiujitsu', 179, 'short', '{guarda}', '{}', null),
  ('x1IAucGQebY', 'Feliz dia do faixa preta!  #bjj #jiujitsu', 17, 'short', '{competicao}', '{}', 'marrom'),
  ('bUZcuh4_nwk', 'Pegadas no jiu jitsu #bjj #jiujitsu', 91, 'short', '{controle}', '{}', null),
  ('NBV6aIlK3gI', 'Como está seu posicionamento? #bjj #jiujitsu', 106, 'short', '{geral}', '{}', null),
  ('A9b739cDmlE', 'Se fizer justo, não tem como defender. Oss! #bjj #jiujitsu', 94, 'short', '{defesa}', '{}', null),
  ('uvrY0k5n6T8', 'A energia do poder de dominação. Você já dominou outra pessoa com controle absoluto? #jiujitsu #bjj', 118, 'short', '{controle}', '{}', null),
  ('aIb4vjjGFuk', 'Como abrir a guarda fechada #bjj #jiujitsu', 97, 'short', '{guarda}', '{guarda_fechada}', null),
  ('_yCW__mG4kU', 'Como passar a Guarda aranha + armlock #jiujitsu #bjj', 33, 'short', '{finalizacao,passagem,guarda}', '{guarda_aberta}', null),
  ('wGBmVTJuI5U', 'Como fazer um ude garami na guarda fechada #bjj #jiujitsu', 57, 'short', '{guarda}', '{guarda_fechada}', null),
  ('YEbDsm3ktRA', 'Como ter mais gás no JIU jitsu', 130, 'short', '{fisico}', '{}', null),
  ('PJ5yUkTb41U', 'Luta em pé', 68, 'short', '{competicao}', '{em_pe}', null),
  ('-xfifPFx0IA', 'Mão de vaca / chave de punho 🤡 #bjj #jiujitsu', 14, 'short', '{finalizacao}', '{}', null),
  ('BmiTWuRbz1Y', 'Armlock da fechada #bjj #jiujitsu', 164, 'short', '{finalizacao}', '{}', null),
  ('i1H-YCombdA', 'Como fazer estrangulamento X na fechada #jiujitsu #bjj', 65, 'short', '{finalizacao}', '{}', null),
  ('pOJqv9c8dro', 'Jiujitsu para iniciantes. Alavancas #bjj #jiujitsu', 102, 'short', '{geral}', '{}', null),
  ('QfFFdAFfAdw', 'Domine Combate: A Estratégia de Quebrar Postura Essencial! #shorts', 59, 'short', '{logica}', '{}', null),
  ('Ei_4P0jpa6M', 'Finalização Surpresa nas Costas: Técnica Secreta do Jiu-Jitsu #shorts', 68, 'short', '{finalizacao,controle}', '{costas}', null),
  ('JbIVMYpiJGk', 'Alavanca no jiu-jítsu na prática #bjj #jiujitsu', 116, 'short', '{geral}', '{}', null),
  ('plUaoZFxBmQ', '#bjj #jiujitsu #humor', 10, 'short', '{geral}', '{}', null),
  ('LzvsRfruMKk', 'Como abrir e passar uma guarda fechada #bjj #jiujitsu', 121, 'short', '{passagem,guarda}', '{guarda_fechada}', null),
  ('zNb_9lyYd8k', 'Domine a Kimura: Técnica Essencial no Jiu Jitsu #shorts', 98, 'short', '{finalizacao}', '{}', null),
  ('bw2ZBuDHz64', 'Raspagem de laço #bjj #jiujitsu', 76, 'short', '{raspagem}', '{guarda_aberta}', null),
  ('B6X8H8kXbPY', 'Nem queria mas já que você insiste 🤣#jiujitsu #bjj #humor', 4, 'short', '{geral}', '{}', null),
  ('dNVPGN93cW0', 'Aprenda a fazer omoplata #bjj', 69, 'short', '{finalizacao}', '{}', null),
  ('TvhZMZ-lEWE', 'Jiu jitsu é sobre dominar o outro. Dominar é o objetivo. Finalizar é consequência #jiujitsu #bjj', 26, 'short', '{logica,finalizacao}', '{}', null),
  ('xGQIt_P7_Xg', 'Gosta da luta em pé? Link na bio #jiujitsu #bjj #judo', 54, 'short', '{queda,competicao}', '{em_pe}', null),
  ('YgmsB2jcQaw', 'Saiu aula nova de guarda aberta na plataforma. Entenda a lógica.Link na bio #jiujitsu #bjj #bjjgirls', 70, 'short', '{logica,guarda}', '{guarda_aberta}', null),
  ('zW3gwnUPXGM', 'Você chamou o Mestrao na guarda #bjj #jiujitsu', 71, 'short', '{guarda}', '{}', null),
  ('AZQTRE9sCRk', 'Como fazer armlock sem machucar o ovo #bjj', 62, 'short', '{finalizacao}', '{}', null),
  ('d8_F7SOklyc', 'Como começar a rolar de joelhos #bjj #jiujitsu', 103, 'short', '{geral}', '{}', null),
  ('bUUgKpS8isY', 'Jiu jitsu em primeira pessoa. Entenda a lógica #bjj #jiujitsu', 88, 'short', '{logica}', '{}', null),
  ('d19YUY3wrWM', 'Jiujitsu para inteligentes. Link na bio  #bjj #jiujitsu', 44, 'short', '{geral}', '{}', null),
  ('qDSNfQ4Tmd0', 'Jiujitsu para iniciantes - faixa branca #bjj #jiujitsu', 108, 'short', '{competicao}', '{}', 'branca'),
  ('UFoiblyQQUU', 'Guardada aranha + armlock surpresa #bjj #isuckatjiujitsushow', 25, 'short', '{finalizacao,guarda}', '{guarda_aberta}', null),
  ('tbNB9vPhItY', 'Sobre jiujitsu #bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('b7iZ3ska4-U', 'Sobre jiujitsu #jiujitsu #bjj', 60, 'short', '{geral}', '{}', null),
  ('lGVL8IRvb-s', 'Sobre jiujitsu #bjj', 60, 'short', '{geral}', '{}', null),
  ('jM2hvLfgPuk', 'Como evoluir no jiu-jítsu #bjj #jiujitsu', 120, 'short', '{geral}', '{}', null),
  ('yD8Vkh5SEEA', 'Sobre jiujitsu #bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('7fLF99SxVwg', 'Sobre jiujitsu #bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('xrv3Exdow7E', 'Sobre jiujitsu #bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('mtHaD5AxphM', 'Sobre jiujitsu #bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('Ob7ZyYtB-0Q', '#bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('aYKF5i790tc', 'Treino se comenta? #bjj', 157, 'short', '{geral}', '{}', null),
  ('qrVvvtq5Mhg', '#bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('VBOjPHgsAe0', 'Jiu jitsu tá fácil de aprender #bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('6hzDGUKBRdo', 'O melhor treino para gás no jiu-jítsu é o treino de jiu-jítsu #jiujitsu #bjj', 60, 'short', '{fisico}', '{}', null),
  ('pHvdSqbUr3U', 'JIU JITSU- como rolar sentado', 121, 'short', '{geral}', '{}', null),
  ('FTZjjY7DYW4', 'Jiu-Jitsu: Domine a Arte de Passar Guarda com Tática! #shorts', 54, 'short', '{passagem,guarda}', '{}', null),
  ('m--OEAy9wew', 'Vetores de força no JIU JITSU #bjj', 151, 'short', '{fisico}', '{}', null),
  ('uQhiA5TC77U', '#jiujitsu #bjj', 59, 'short', '{geral}', '{}', null),
  ('uf_YAZW9ZnA', 'Quais guardas um faixa azul deve saber?#jiujitsu #bjj', 59, 'short', '{guarda,competicao}', '{}', 'azul'),
  ('gR3o0JSZQMk', 'Jiu jitsu para iniciantes #jiujitsu #bjj', 60, 'short', '{geral}', '{}', null),
  ('ApsvqNTlO-A', 'Controle Corporal: Segredo do Joelho para Lutar Melhor #shorts', 126, 'short', '{controle,competicao}', '{}', null),
  ('09R6LbM_ThQ', 'Domine o Combate: Desequilíbrio e Controle Essencial #shorts', 168, 'short', '{queda,controle,fisico}', '{}', null),
  ('1ebPKZW0MBE', '#jiujitsu #bjj', 59, 'short', '{geral}', '{}', null),
  ('Jkue4VNMc_Y', '#jiujitsu #bjj', 60, 'short', '{geral}', '{}', null),
  ('iPZ7uEJgEX0', 'Jiu-Jitsu: Intenção, Consciência e Conforto no Tatame #shorts', 71, 'short', '{geral}', '{}', null),
  ('7g6crJAE45U', 'Vetores de força no jiu-jítsu #jiujitsu #bjj', 153, 'short', '{fisico}', '{}', null),
  ('LcYVk_jIT7k', 'O que você diria para esse azul? #jiujitsu #bjj', 60, 'short', '{geral}', '{}', null),
  ('F9f8g7VmLlo', 'E treina musculação pra ficar forte também kakakaka #jiujitsu #bjj', 60, 'short', '{geral}', '{}', null),
  ('OgLEGHXFwac', 'O que ninguém te conta sobre finalizar #bjj', 168, 'short', '{finalizacao}', '{}', null),
  ('QYwFacdCvsQ', '#jiujitsu #bjj', 26, 'short', '{geral}', '{}', null),
  ('Vx2EhXRkW_4', 'Jiujitsu em câmera lenta #bjj #jiujitsu', 178, 'short', '{geral}', '{}', null),
  ('jDvALqCTiEo', 'Jiu jitsu em câmera lenta #bjj #jiujitsu', 126, 'short', '{geral}', '{}', null),
  ('FOgUSp407-c', 'Jiu jiu é sobre dominar para finalizar #bjj #jiujitsu', 142, 'short', '{logica,finalizacao}', '{}', null),
  ('KUmiY7BwKWs', 'o segredo para finalizar #bjj', 159, 'short', '{finalizacao}', '{}', null),
  ('vi42-v3oPqE', 'Gostou do conteúdo? Segue pra mais #bjj #jiujitsu', 155, 'short', '{geral}', '{}', null),
  ('fAPzSIGXALo', 'Xadrez humano #bjj', 40, 'short', '{geral}', '{}', null),
  ('EtF2SUAEznw', 'O 3º grau chegou #bjj', 33, 'short', '{competicao}', '{}', null),
  ('zQzeClVsuwM', 'Qual seu tipo de treino favorito? #bjj #jiujitsu', 57, 'short', '{geral}', '{}', null),
  ('VcIPzIa_8ko', '#bjj #fundamentosdojiujitsu', 98, 'short', '{logica}', '{}', null),
  ('gEfWW6SYTJY', 'Chave de Pé ou Triângulo? O Giro que Confunde Tudo! #shorts', 43, 'short', '{finalizacao}', '{em_pe,perna}', null),
  ('Ygyf5keOYt4', 'Domine o Osotogari: Técnica de Queda de Jiu-Jitsu Revelada! #shorts', 89, 'short', '{queda}', '{em_pe}', null),
  ('8e5dblfIDqg', 'Domine a Guarda: A Chave para Derrubar oponentes mais Fortes! #shorts', 74, 'short', '{queda,guarda}', '{}', null),
  ('NXTwpNpjkXA', 'Domine a Postura e o Equilíbrio: A Chave Para o Jiu-Jitsu Vencer #shorts', 95, 'short', '{fisico}', '{}', null),
  ('MyqP4acimhU', 'Domine 100kg: A Pressão no Ombro Que Finaliza o Jogo! #shorts', 140, 'short', '{finalizacao,controle}', '{cem_quilos}', null),
  ('e846OVL8l0Y', 'Quebre a Força do Oponente com Essa Técnica de Jiu-Jitsu! #shorts', 78, 'short', '{fisico}', '{}', null),
  ('sxpKGCuESj4', 'Domine a Pegada e Fuja da Mão de Vaca no Jiu-Jitsu! #shorts', 63, 'short', '{controle}', '{}', null),
  ('g-xxfOE8V1Q', 'Domine a Chave de Pé: O Segredo do Jiu-Jitsu Revelado! #shorts', 144, 'short', '{finalizacao}', '{em_pe,perna}', null),
  ('dI6AJwiljYI', 'Técnica Secreta: Suporte de Peso Sem Esforço #shorts', 69, 'short', '{geral}', '{em_pe}', null),
  ('HbplQ3GdhkE', 'Atacar tirando possibilidades de defesa é ser perigoso #bjj', 58, 'short', '{defesa}', '{}', null),
  ('mshz9COU4PA', 'Medo Gera Rigidez: Como O Conhecimento Liberta #shorts', 38, 'short', '{geral}', '{}', null),
  ('J9OTWw2VzlE', 'Liberte-se de Pegadas Fortes: Técnica Sem Força Revelada! #shorts', 87, 'short', '{controle,fisico}', '{em_pe}', null),
  ('3eHFkWzJmQY', 'Jiu-Jitsu Inteligente: Domine com Alavancagem, Não Força #shorts', 107, 'short', '{fisico}', '{}', null),
  ('NBhhk5EhLCk', 'Anatomia do estrangulamento sanguíneo #bjj #jiujitsu', 76, 'short', '{finalizacao}', '{}', null),
  ('lx4NZJLK4vw', 'Um tenta lembrar e o outro decide! #bjj #jiujitsu', 12, 'short', '{geral}', '{}', null),
  ('R09CYCsruqY', 'Jiu-Jitsu: Domine a Articulação com Pressão e Ângulo! #shorts', 45, 'short', '{controle}', '{}', null),
  ('dYXaemlGFug', 'Jiu-Jitsu: Domine o Oponente com Distribuição de Peso Estratégica! #shorts', 85, 'short', '{geral}', '{em_pe}', null),
  ('jN-RBAKCFu4', 'Como treinar com atletas? #bjj #jiujitsu', 68, 'short', '{geral}', '{}', null),
  ('o1cDLeaBWJA', 'Domine o Jiu Jitsu: Evite o Sweep e Garanta a Passagem Implacável! #shorts', 67, 'short', '{passagem}', '{}', null),
  ('Q9IqMO6k4Mc', '#faixabranca #jiujitsu #bjj', 50, 'short', '{competicao}', '{}', null),
  ('fwWTofvls9k', 'O que te sobraria de jiu jitsu se eu tirasse tua força? #bjj #jiujitsu', 5, 'short', '{fisico}', '{}', null),
  ('DrHgGq4oxZE', 'Protejam as cabeças #bjj #jiujitsu #humor', 68, 'short', '{geral}', '{}', null),
  ('qH_UuKEUz9A', 'Como parar de apanhar no JIU Jitsu #bjj #jiujitsu.', 84, 'short', '{defesa}', '{}', null),
  ('xpXpxsm08Co', 'Jiu-jítsu para iniciantes 100 kg  #bjj #jiujitsu', 42, 'short', '{controle}', '{cem_quilos}', null),
  ('5g5Lo8xm-Zo', 'Porque você não lembra posições no rola #bjj #jiujitsu', 70, 'short', '{logica}', '{}', null),
  ('uXl3iA-EcfA', 'Nem sempre a vai acontecer como você quer, por isso é importe entender a estrutura da raspagem #bjj', 48, 'short', '{logica,raspagem}', '{}', null),
  ('kLfezkZ2mMs', 'Erros do triângulo #bjj #jiujitsu #triangulo', 134, 'short', '{finalizacao}', '{}', null),
  ('aeMSE0Hue-I', 'Segredos do Judô Revelados! #jiujitsu #bjj', 128, 'short', '{queda}', '{}', null),
  ('UQGfHYUKJpQ', 'Mais uma vez 🤡😹 #bjj #jiujitsu', 36, 'short', '{geral}', '{}', null),
  ('091lkGNbpJ0', 'Jiu-jítsu para iniciantes e avançados #jiujitsu', 41, 'short', '{geral}', '{}', null),
  ('TWxIgNFE22I', 'O que o professor leva em consideração na hora de graduar? #bjj #jiujitsu', 60, 'short', '{geral}', '{}', null),
  ('BKcgrlQliFs', 'Pombo passador #bjj #jiujitsu', 57, 'short', '{geral}', '{}', null),
  ('X-XFjklCp4Y', 'Pegadas #bjj #jiujitsu', 86, 'short', '{controle}', '{}', null),
  ('JoTKucPvT1Q', 'Quem faz jiu precisa fazer musculação? #jiujitsu #bjj', 53, 'short', '{geral}', '{}', null),
  ('ulvN-O_mMDc', '#jiujitsu #bjj #humor', 33, 'short', '{geral}', '{}', null),
  ('wc7_16-MIVY', 'A mente do master #jiujitsu #humor #bjj', 27, 'short', '{geral}', '{}', null),
  ('jcOkBWYqQYg', 'Controle Total: Use Seu Corpo Inteiro, Não Só as Mãos! #shorts', 54, 'short', '{controle}', '{}', null),
  ('b1mpmSzgjmk', 'Neurojitsu: A Revolução do Jiu-Jitsu que Você Precisa Conhecer! #shorts', 77, 'short', '{geral}', '{}', null),
  ('PCgBjlwIiqg', 'Jiu-jítsu para iniciantes #jiujitsu #bjj', 33, 'short', '{geral}', '{}', null),
  ('sBU4ttEQqU0', 'Desafiou o mestre #jiujitsu #bjj', 43, 'short', '{geral}', '{}', null),
  ('0IFQPoIyDZc', 'Judô: Antecipe a Queda do Adversário Com Essa Estratégia #shorts', 74, 'short', '{logica,queda}', '{em_pe}', null),
  ('cLIutAykaGI', 'Seminário para faixas brancas- Neuro Jitsu', 62, 'short', '{competicao}', '{}', null),
  ('5XevOWIRZaE', 'Jiu-Jitsu: Perder o Medo de Rolar e Dominar Quedas! #shorts', 60, 'short', '{logica,queda}', '{em_pe}', null),
  ('mKdq1IHFqjg', 'Aprenda Amortecimento de Quedas: Judô Passo a Passo! #shorts', 139, 'short', '{queda}', '{em_pe}', null),
  ('1oEqME6wfbY', 'Jiu-Jitsu: Pés Paralelos para Guarda e Defesa (Guia Completo) #shorts', 39, 'short', '{defesa,guarda}', '{}', null),
  ('kEhFFjoUTKM', 'Jiu-Jitsu: Origens, Evolução e o Caminho Brasileiro #shorts', 83, 'short', '{geral}', '{}', null),
  ('Hy4EI2S2iN8', 'Koshiguruma: A Técnica Incrível de Judô para Derrubar! #shorts', 49, 'short', '{queda}', '{}', null),
  ('PfMDH7ylwt8', 'Curso de Arbitragem: Aprenda as Regras e Pontuações! #shorts', 24, 'short', '{geral}', '{}', null),
  ('G7_qCvzHees', 'Jiu-Jitsu: Quebrando a Guarda Fechada com Técnica e Força #shorts', 74, 'short', '{guarda,fisico}', '{guarda_fechada}', null),
  ('n6RVH9rjcXA', 'Jiu-Jitsu: Aprenda a Diferença Crucial na Pegada OGosh! #shorts', 96, 'short', '{controle}', '{}', null),
  ('hoqDGYEVJRY', 'Armlock Surpreendente: A Técnica Inovadora Revelada! #shorts', 39, 'short', '{finalizacao}', '{}', null),
  ('nvNHaW7_HzA', 'Osotogari: Aprenda a Técnica de Judô em Movimento! #shorts', 87, 'short', '{queda}', '{em_pe}', null),
  ('yulVIL9IIoU', 'Guarda de Mão: A Chave para Quedas no Judô! #shorts', 143, 'short', '{queda,guarda}', '{em_pe}', null),
  ('5_W-072cV5I', 'Aulas Diárias: Segredo para Absorver Conteúdo Profundamente #shorts', 76, 'short', '{geral}', '{}', null),
  ('6m1XdJpQT0I', 'Jiu Jitsu: Quedas, Guardas e Posições de Domínio! #shorts', 42, 'short', '{queda,guarda}', '{em_pe}', null),
  ('RsKJnNZ4uc8', 'Double Leg em Jiu-Jitsu: Estratégia e Técnica Poderosa #shorts', 28, 'short', '{logica}', '{}', null),
  ('X9qnj353hu4', 'Aumente Sua Velocidade: Estratégias de Movimentos no Esporte #shorts', 70, 'short', '{logica}', '{}', null),
  ('P3mRR2fN-8Y', 'Jiu-Jitsu: Estratégias de Ataque e Defesa no Chão! #shorts', 44, 'short', '{logica,defesa}', '{}', null),
  ('P8TRkX-qT5w', 'Aula Digital: Estratégias Únicas para Professores Online! #shorts', 58, 'short', '{logica}', '{}', null),
  ('Vh32Qx47ZAA', 'Finalização no Jiu-Jitsu: Estratégia do Triângulo Mortal! #shorts', 26, 'short', '{logica,finalizacao}', '{}', null),
  ('C-6H6Pjm_yE', 'Aprenda a Fazer a Mochila de Kimono: Guia Prático! #shorts', 161, 'short', '{geral}', '{}', null),
  ('Ucx3x4bSx98', 'Como é o seu? #jiujitsu #bjj', 26, 'short', '{geral}', '{}', null),
  ('Y9H4gCrew60', 'Jiu-Jitsu: Domine as 100 kg e Aumente Suas Chances! #shorts', 68, 'short', '{controle}', '{cem_quilos}', null),
  ('g7x8-jhpH6E', 'Jiu-Jitsu 100 Kilos: Domine a Posição com Esta Estratégia! #shorts', 93, 'short', '{logica}', '{}', null),
  ('wqeGlUMMdOA', 'Combate Lógico: A Estratégia Defensiva Essencial #shorts', 154, 'short', '{logica}', '{}', null),
  ('GUmrRRzP7Ho', 'Como Lavar Kimono: Dicas da Especialista para Durar Mais! #shorts', 103, 'short', '{geral}', '{}', null),
  ('BnUcmvx2DL0', 'Domine a Luta: Estratégias Poderosas no Jiu-Jitsu! #shorts', 43, 'short', '{logica,competicao}', '{}', null),
  ('GEQPyzQOiSM', 'Passando a Guarda: Estratégias e Comportamentos Essenciais #shorts', 58, 'short', '{logica,passagem,guarda}', '{}', null),
  ('jfRyMxfcluo', 'Jiu-Jitsu: Domine a Luta com Intenção e Estratégia! #shorts', 41, 'short', '{logica,competicao}', '{}', null),
  ('DSA9ff4rVyI', 'Kimono Duro: Como Cuidar e Evitar Estragos (Dicas) #shorts', 97, 'short', '{geral}', '{}', null),
  ('SpCQLwa31X8', 'Jiu-Jitsu: Fundamentos Essenciais Para Uma Base Sólida! #shorts', 103, 'short', '{logica}', '{}', null),
  ('lfKnGPwNzj8', '100kg no JIU JITSU', 124, 'short', '{controle}', '{cem_quilos}', null),
  ('XeFjd4TqI7w', 'Sua arma principal não pode ser a força!', 31, 'short', '{fisico}', '{}', null),
  ('gDNFdoxljdc', 'Os estudos só começaram! #bjj', 41, 'short', '{geral}', '{}', null),
  ('YbIMsZE-ZR8', 'Faixa Azul no Jiu-Jitsu: Seu Poder e Mentalidade Vencedora! #shorts', 71, 'short', '{logica,competicao}', '{}', 'azul'),
  ('0yfj2JMiaZc', 'Jiu-Jitsu: Encontre Paz e Conforto na Sua Jornada! #shorts', 71, 'short', '{geral}', '{}', null),
  ('JI6REkRZrE8', 'Converse com o Professor: Dicas Para Superar Medos #shorts', 88, 'short', '{geral}', '{}', null),
  ('yjrLYNJ3dlk', 'Jiu Jitsu- ida para costas', 69, 'short', '{controle}', '{costas}', null),
  ('DAPPXgYJ-7g', 'Manga e Distância: Estratégia no YouTube para Você! #shorts', 51, 'short', '{logica,drill}', '{}', null),
  ('pNiYW3AcU6M', 'Jiu Jitsu- caminho para as costas', 77, 'short', '{controle}', '{costas}', null),
  ('ZAdZQB1vMGg', 'Desgaste Extremo: A Primeira Competição e Seus Desafios! #shorts', 23, 'short', '{fisico,competicao}', '{}', null),
  ('FtjUxywtV10', 'Economize Energia no Combate: Estratégias Essenciais #shorts', 41, 'short', '{logica}', '{}', null),
  ('8FU0-3Cz2rs', 'Jiu-Jitsu: Posição do Quadril e Estratégias de Combate #shorts', 65, 'short', '{logica,fisico}', '{}', null),
  ('EhTZlQU7Sds', 'Finalização com Faixa: Regras Oficiais e Dicas! #shorts', 54, 'short', '{finalizacao,competicao}', '{}', null),
  ('XJOKpBgupDQ', 'Dominando a Guarda: Movimentos Cruciais no Jiu-Jitsu #shorts', 33, 'short', '{guarda}', '{}', null),
  ('UZb7mRsIjS8', 'Jiu-Jitsu: Lições Para Superar Desafios na Vida! #shorts', 31, 'short', '{geral}', '{}', null),
  ('WtVdOvhX3vY', 'Jiu-Jitsu: Estratégia de Contrapeso e Domínio no Combate #shorts', 46, 'short', '{logica}', '{}', null),
  ('WzyQQ8KYtLM', 'Gola estratégica: Como ela afeta seu equilíbrio e postura #shorts', 19, 'short', '{finalizacao,fisico}', '{}', null),
  ('mWcGeJTZNrU', 'Jiu-Jitsu: Supere Desafios e Evolua como Pessoa! #shorts', 63, 'short', '{geral}', '{}', null),
  ('KRSAj-5YVVk', 'Exercício de Alinhamento: A Técnica da Faixa para Equilíbrio #shorts', 40, 'short', '{fisico,drill,competicao}', '{}', null),
  ('kO67RC8doU4', 'Defesa na Guarda Fechada: Estratégia Crucial para Iniciantes! #shorts', 23, 'short', '{logica,defesa,guarda}', '{guarda_fechada}', null),
  ('SY62CxLG_pg', 'Jiu-Jitsu: Compare-se a Você! Evolua SEM Parar! #shorts', 25, 'short', '{geral}', '{}', null),
  ('3utk0D4nPJo', 'Defesa Pessoal: Aprenda a Dominar a Técnica! #shorts', 21, 'short', '{logica,defesa}', '{}', null),
  ('OW2TkkcA-_w', 'Jiu-Jitsu: Estratégia de Guarda e Domínio na Luta #shorts', 39, 'short', '{logica,guarda,competicao}', '{}', null),
  ('xgZCEUxdVGM', 'Controle de Braço: Técnicas Essenciais para Quebrar Postura #shorts', 28, 'short', '{controle}', '{}', null),
  ('2DusDxAlLtc', 'Aprenda Jiu-Jitsu: Metodologia e Coordenação Essenciais #shorts', 78, 'short', '{geral}', '{}', null),
  ('MuhhAAFbTGo', 'Tsuri-goshi: Domine a Técnica de Judô para Quedas! #shorts', 19, 'short', '{queda}', '{em_pe}', null),
  ('LT8Sl5AHNM4', 'Dominando a Posição: Estratégias de Luta no Octógono #shorts', 26, 'short', '{logica,competicao}', '{}', null),
  ('dB_s3dYUTrY', 'Jiu-Jitsu: Segredo do Quadril e Guarda Imbatível! #shorts', 160, 'short', '{guarda,fisico}', '{}', null),
  ('ReDK1A0Qo_A', 'Professor de Jiu-Jitsu: O Termômetro Essencial da Sua Aula #shorts', 89, 'short', '{geral}', '{}', null),
  ('-BjyHFI6qQo', 'Queda Inesperada: A Técnica Secreta do Faixa Branca! #shorts', 27, 'short', '{queda,competicao}', '{em_pe}', 'branca'),
  ('WHyIElhwAVU', 'Estratégia de Luta: Análise da Pegada e Mobilidade no Ringue #shorts', 33, 'short', '{logica,controle,fisico,competicao}', '{}', null),
  ('PDXKaFBC9ik', 'Guarda Fechada: Estratégias Essenciais para Economizar Energia #shorts', 112, 'short', '{logica,guarda}', '{guarda_fechada}', null),
  ('t1sEpysJb5A', 'Faixa Preta é Professor? A Verdade no Jiu-Jitsu! #shorts', 37, 'short', '{competicao}', '{}', 'marrom'),
  ('zwH-ZLiAheI', 'Técnicas de Defesa: Como Baixar o Peso no Judô #shorts', 27, 'short', '{defesa,queda}', '{}', null),
  ('Vwhr9bLi2pc', 'Jiu-Jitsu: A Técnica de Queda Perfeita em Detalhes! #shorts', 27, 'short', '{queda}', '{em_pe}', null),
  ('OP7k2do2BmM', 'Jiu-Jitsu: Desequilíbrio Estratégico para Controlar o Oponente #shorts', 43, 'short', '{queda,controle,fisico}', '{}', null),
  ('LGXkugL5ucc', 'Aprendizados Únicos: Surpreenda-se e Pare de Se Comparar! #shorts', 74, 'short', '{geral}', '{}', null),
  ('sKzXX70i8hw', 'Ogoshi Perfeito: Projeção com Técnica no Judô! #shorts', 35, 'short', '{queda}', '{}', null),
  ('RfnGmWdwocQ', 'Posição Confortável vs. Mobilidade: Análise Profunda! #shorts', 24, 'short', '{fisico}', '{}', null),
  ('31M3i-tV_3s', 'Segredo do Jiu-Jitsu: Domine o Controle de Guarda! #shorts', 22, 'short', '{controle,guarda}', '{}', null),
  ('VPv-uu1pf84', 'Artes Marciais: Encontre a Escola Certa para Você! #shorts', 86, 'short', '{geral}', '{}', null),
  ('903MPFOmmAM', 'Defesa de Uchi Gari: Estratégia e Centro de Gravidade #shorts', 62, 'short', '{logica,defesa}', '{}', null),
  ('bOeDfxDN-kY', 'Técnicas de Guarda: Estratégias e Análise no Combate! #shorts', 24, 'short', '{logica,guarda}', '{}', null),
  ('w-b-yaJGzYI', 'Como Livrar a Perna: Estratégia de Queda no Jiu-Jitsu #shorts', 21, 'short', '{logica,queda}', '{em_pe}', null),
  ('tQQD3MUHniI', 'Dominando a Guarda: Pegada Cruzada para Quebrar a Postura #shorts', 72, 'short', '{controle,guarda}', '{}', null),
  ('VwnlDIGO7zk', 'A Verdade Sobre Treino: Minha Jornada e Dicas Essenciais! #shorts', 66, 'short', '{geral}', '{}', null),
  ('nKYaVmPSEWQ', 'Técnicas de Luta: Domine o Quadril do Adversário! #shorts', 158, 'short', '{fisico,competicao}', '{}', null),
  ('SRqKS4nXqd0', 'Campeonato com Massa e Julião: Crescimento e Evolução! #shorts', 40, 'short', '{competicao}', '{}', null),
  ('Px3o2YfIMgM', 'Técnica de Mudança: Movimentação e Estratégia no Jogo #shorts', 19, 'short', '{logica,drill}', '{}', null),
  ('uXVEaWNdcdg', 'Evolua Seu Jogo: Dicas para Manter a Calma e Crescer #shorts', 45, 'short', '{geral}', '{}', null),
  ('wQ1cdm6-RNE', 'Jiu-Jitsu e Judô: A Jornada Incrível de um Atleta! #shorts', 100, 'short', '{queda}', '{}', null),
  ('RKUWhePYhvU', 'Jiu-Jitsu: Domine a Guarda com Pegadas Estratégicas! #shorts', 122, 'short', '{controle,guarda}', '{}', null),
  ('L3pAAUG23Gk', 'Raspagem no Jiu-Jitsu: Análise da Queda e Passagem #shorts', 28, 'short', '{passagem,raspagem,queda}', '{em_pe}', null),
  ('ZXlUl-zenk8', 'Jiu-Jitsu: Finalizando com Pegada na Gola e Estrangulamento! #shorts', 16, 'short', '{finalizacao,controle}', '{}', null),
  ('lbg923kqVmc', 'Jiu-Jitsu: Nem Todos São Adeptos? Reflexões e Análise #shorts', 130, 'short', '{geral}', '{}', null),
  ('XBUSZ6klYe0', 'Faixa no Sumô: Segredo do Equilíbrio e Força! #shorts', 41, 'short', '{fisico,competicao}', '{}', null),
  ('fH4D8Uiju9c', '100 KG no chão: Estratégia de defesa e recuperação! #shorts', 34, 'short', '{logica,defesa,controle}', '{cem_quilos}', null),
  ('99lgiPuSQgM', 'Pegada no Jiu-Jitsu: Conectando e Antecipando Movimentos #shorts', 46, 'short', '{logica,controle}', '{}', null),
  ('e94Qiz0xqG4', 'Faixa no Judô: Técnicas, Sumô e Centro de Gravidade! #shorts', 113, 'short', '{queda,competicao}', '{}', null),
  ('4obH14pOICs', 'Guarda na Luta: Análise e Estratégias para Vencer #shorts', 42, 'short', '{logica,guarda,competicao}', '{}', null),
  ('6e1dddObwxY', 'Análise Estratégica: Posição Arriscada e Vantagens no Jogo #shorts', 24, 'short', '{geral}', '{}', null),
  ('NCzLkp-N1yY', 'Jiu-Jitsu: Aprenda a Técnica da Americana Incrível! #shorts', 29, 'short', '{finalizacao}', '{}', null),
  ('NvqCGlLM5hI', 'Jiu-Jitsu: Do Silêncio à Guerra, Sua Jornada no Japão #shorts', 38, 'short', '{geral}', '{}', null),
  ('KZDMtyBOblI', 'Guarda no Jiu-Jitsu: Estratégias e Técnicas Essenciais #shorts', 47, 'short', '{logica,guarda}', '{}', null),
  ('Lp4DO_7RzdY', 'Movimento de Jiu-Jitsu: Domine a Queda e Finalize! #shorts', 32, 'short', '{queda}', '{em_pe}', null),
  ('-WfutsF7AW8', 'Minha Jornada: Capoeira, Judô e Jiu-Jitsu! #shorts', 70, 'short', '{queda}', '{}', null),
  ('hl5jZvP0dbY', 'Guarda-laço Armada: Desequilíbrio Explosivo no Jiu-Jitsu #shorts', 24, 'short', '{queda,guarda,fisico}', '{guarda_aberta}', null),
  ('KxspPoxEzrg', 'Jiu-Jitsu: Estratégias e Limites de Peso no Combate #shorts', 31, 'short', '{logica}', '{em_pe}', null),
  ('qB9IId2sB-U', 'Triângulo Fechado: Finalização e Estratégias Incríveis #shorts', 33, 'short', '{logica,finalizacao}', '{}', null),
  ('fpthy09rJkk', 'Queda Perigosa! Análise do Peso e Movimentos no Jiu-Jitsu #shorts', 25, 'short', '{queda}', '{em_pe}', null),
  ('aoOCvlJtdrY', 'Estratégia de Combate: Análise do Retorno e Domínio #shorts', 32, 'short', '{logica}', '{}', null),
  ('QIaNiziHp5M', 'Jiu-Jitsu: A Fascinante História e Filosofia por Trás! #shorts', 55, 'short', '{logica}', '{}', null),
  ('KHIbe6gWfvU', 'Técnica de Ashi: Domine o Desequilíbrio no Combate! #shorts', 23, 'short', '{queda,fisico}', '{perna}', null),
  ('UfhZCQmzPug', 'Jiu-Jitsu: Dominando o Abdômen com Pressão e Ângulo #shorts', 50, 'short', '{controle}', '{}', null),
  ('U6-C89h5uvg', 'Erro Crítico: O Momento Decisivo no Movimento! #shorts', 37, 'short', '{geral}', '{}', null),
  ('sgfUDLW0OeU', 'Velocidade e Visão: A Incrível Luta! Veja Agora! #shorts', 29, 'short', '{competicao}', '{}', null),
  ('TsXa_0okYsY', 'Felicidade e Paz: Minha Vida Sem Brigas e Conflitos #shorts', 24, 'short', '{fisico}', '{}', null),
  ('x2OnAuPUdVk', 'Deashi Harai: A Técnica Secreta do Judô Revelada! #shorts', 79, 'short', '{queda}', '{perna}', null),
  ('hg0okrBvKCY', 'Defesa Pessoal: Estratégias Cruciais Para Proteger Seu Rosto #shorts', 61, 'short', '{logica,defesa}', '{}', null),
  ('ErBoV-DRQqs', 'Jiu-Jitsu Americana: Técnica Incrível Passo a Passo! #shorts', 45, 'short', '{finalizacao}', '{}', null),
  ('IwXsWmw3yoY', 'Meia Guarda: Domine a Posição e Escape Facilmente #shorts', 30, 'short', '{guarda}', '{meia_guarda}', null),
  ('xVD0C2BH21s', 'Aprenda a se defender: Lições do meu primeiro professor #shorts', 21, 'short', '{defesa}', '{}', null),
  ('_n6Bg78EobU', 'Comparando Pesos na Luta: Estratégias e Velocidade #shorts', 48, 'short', '{logica,competicao}', '{}', null),
  ('oFD8azrrgOQ', 'Jiu-Jitsu: A Chave da Passagem Pro Braço Livre! #shorts', 50, 'short', '{passagem}', '{}', null),
  ('E5j-gQy_RMQ', 'Posição de Jiu-Jitsu: Detalhes e Treinamento Passo a Passo #shorts', 43, 'short', '{geral}', '{}', null),
  ('FMpb4EHQVjc', 'Meia Guarda: Detalhes Cruciais para Dominar por Dentro! #shorts', 31, 'short', '{logica,guarda}', '{meia_guarda}', null),
  ('0kLgX8dxDKA', 'Treinamento Transforma: Caráter e Defesa Pessoal em Ação! #shorts', 118, 'short', '{defesa}', '{}', null),
  ('9dIPhJtXxp4', 'Jiu-Jitsu: Técnica Ashi-Waza para Atletas com Pernas Longas #shorts', 49, 'short', '{fisico}', '{perna}', null),
  ('BPDueZf9yTw', 'Escape do Triângulo: Defesa e Contra-Ataque no Jiu-Jitsu #shorts', 135, 'short', '{finalizacao,defesa}', '{}', null),
  ('qUa7TEdw3Wo', 'Como Rodar o Quadril: Dicas de Movimento Perfeitas! #shorts', 22, 'short', '{fisico}', '{}', null),
  ('e8c4bvmnvjY', 'Desequilíbrio no Jiu-Jitsu: A Chave para o Sucesso Absoluto! #shorts', 36, 'short', '{queda,fisico}', '{}', null),
  ('6mj8hkUjurI', 'Bushidô: Os 7 Dogmas da Honra, Silêncio e Lealdade #shorts', 126, 'short', '{geral}', '{}', null),
  ('JghKCGv10f8', 'Treino de Chute: Movimento Inicial e Técnica Perfeita! #shorts', 52, 'short', '{geral}', '{}', null),
  ('7peNzVZbQ_I', 'Defesa no Jiu-Jitsu: Antecipe o Ataque e Vença! #shorts', 38, 'short', '{logica,defesa}', '{}', null),
  ('TJdgz-9tN-E', 'Triângulo Estratégico: Finalização Imbatível no Jiu-Jitsu! #shorts', 61, 'short', '{finalizacao}', '{}', null),
  ('8uzbkU95Ghg', 'Meia Guarda: Dicas Cruciais para um Domínio Eficaz! #shorts', 80, 'short', '{guarda}', '{meia_guarda}', null),
  ('8vO5q17NL-U', 'Minha Jornada: De Professor de Capoeira aos 18 Anos #shorts', 110, 'short', '{geral}', '{}', null),
  ('v9DFDI3sC2I', 'Movimento do Braço na Luta: Técnica Incrível e Eficaz! #shorts', 26, 'short', '{competicao}', '{}', null),
  ('1KRydUYLD8A', 'Antecipação na Defesa: Guia para o Seu Próximo Nível #shorts', 31, 'short', '{logica,defesa}', '{}', null),
  ('cZ3OZJlvxwk', 'Posição de Jiu-Jitsu: Aprenda a Dominar Essa Técnica! #shorts', 26, 'short', '{logica}', '{}', null),
  ('Yujak-TjYhI', 'Punição no Jiu-Jitsu: Análise da Luta e Regras! #shorts', 56, 'short', '{competicao}', '{}', null),
  ('0peZI6jDVRw', 'Jiu-Jitsu: A Fascinante História e Filosofia por Trás da Luta #shorts', 47, 'short', '{logica,competicao}', '{}', null),
  ('ub66Sp5zLAw', 'Ângulo Perfeito: Desvendando a Técnica da Tentativa! #shorts', 48, 'short', '{geral}', '{}', null),
  ('Lorf0uuaAL8', 'Desafio: Aprenda a Ritmo com 1, 2, Pá! Sem Errar #shorts', 19, 'short', '{geral}', '{}', null),
  ('fxEMhniS2E4', 'Defesa de Triângulo: A Técnica para NÃO Tomar! #shorts', 117, 'short', '{finalizacao,defesa}', '{}', null),
  ('gATB9IJT0Zw', 'Técnica de Jiu-Jitsu: Braço de Cima e Baixo em Ação! #shorts', 35, 'short', '{geral}', '{}', null),
  ('6njklFqKeb8', 'Charles do Bronx: Dias Ruins na Luta e Superação #shorts', 74, 'short', '{competicao}', '{}', null),
  ('iHLfP_TiNaA', 'Empreender nos Treinos: Nossa Visão e Estratégias! #shorts', 29, 'short', '{logica}', '{}', null),
  ('rqWmitxsr-s', 'Desequilibrando 100kg: Técnicas de Defesa Pessoal #shorts', 37, 'short', '{defesa,queda,controle}', '{cem_quilos}', null),
  ('UxGzj0MycGY', 'Técnica de Chute: Aprenda o Tempo Perfeito e Supere! #shorts', 24, 'short', '{drill}', '{}', null),
  ('G8a-EtzKR8s', 'Jiu Jitsu- Faça inteligente! Faça Neurojitsu!', 85, 'short', '{geral}', '{}', null),
  ('1vRJIbLC-Rg', 'Bushidô: O Caminho do Guerreiro e Seus 7 Dogmas #shorts', 49, 'short', '{geral}', '{}', null),
  ('4vYhsFdaK4E', 'Desvendando o Equilíbrio: A Dinâmica da Gangorra! #shorts', 27, 'short', '{fisico}', '{}', null),
  ('pxN8fWMCp-k', 'Quebrando a Postura: Estratégia Imbatível no Combate! #shorts', 37, 'short', '{logica}', '{}', null),
  ('7YR7ykbnohU', 'Bushidô: 7 Dogmas para Uma Vida de Honra e Justiça #shorts', 70, 'short', '{geral}', '{}', null),
  ('gi8L41kFnj8', 'Jiu-Jitsu: Técnicas Incríveis de 100kg #shorts', 58, 'short', '{controle}', '{cem_quilos}', null),
  ('sCiyAmrIixQ', 'Equilíbrio no Jiu-Jitsu: A Chave do Faixa Branca ao Sucesso! #shorts', 29, 'short', '{fisico,competicao}', '{}', 'branca'),
  ('1dS-rW6pSEw', 'O Tatame Revela: Quem Somos de Verdade (Jiu-Jitsu) #shorts', 52, 'short', '{geral}', '{}', null),
  ('Y5dXElWFCRs', 'Exercício de Equilíbrio: Como Controlar o Peso Corporal #shorts', 44, 'short', '{controle,fisico,drill}', '{}', null),
  ('-l0-TbbEcIc', 'Equilíbrio: A Técnica Surpreendente Revelada! #shorts', 26, 'short', '{fisico}', '{}', null),
  ('p0p4jMHNXBo', 'Perseguições e Capoeira: Minha Jornada de Autodefesa #shorts', 48, 'short', '{defesa}', '{}', null),
  ('CUC4-wAnhH8', 'Jiu-Jitsu: Domine o Equilíbrio e Melhore sua Técnica #shorts', 51, 'short', '{fisico}', '{}', null),
  ('NKDHv02KyZY', 'Infância: Brigas de Irmãos e Nossas Reações! #shorts', 44, 'short', '{fisico}', '{}', null),
  ('dZhjjY_7SYk', 'Jiu-Jitsu e Ikigai: Encontre Propósito e Supere Desafios #shorts', 34, 'short', '{geral}', '{}', null),
  ('FoQjLZxwSr8', 'Treino de defesa pessoal: Sinta a diferença na postura e reação! #shorts', 30, 'short', '{defesa}', '{}', null),
  ('OcTdtZoNN8I', 'Jiu-Jitsu: Aprenda a Técnica ''Jogar Fora No Lixo''! #shorts', 21, 'short', '{geral}', '{}', null),
  ('JlBS2JFn7DM', 'Ouchi Gari: Aprenda Jiu-Jitsu e Economize Agora! #shorts', 31, 'short', '{geral}', '{}', null),
  ('Ru94LHKs8qg', 'Punição e Parada na Luta: Entenda o Controle de Cabeça no BJJ #shorts', 17, 'short', '{logica,controle,competicao}', '{}', null),
  ('7ZKry4Mopq0', 'Jiu-Jitsu: A Volta Por Cima no Pior Momento da Minha Vida! #shorts', 95, 'short', '{geral}', '{}', null),
  ('eJf6huZelQ8', 'Postura Perfeita no Jiu-Jitsu: Domine a Defesa e Não Caia! #shorts', 31, 'short', '{defesa}', '{}', null),
  ('GRgMguaxlEE', 'Jiu-Jitsu: A Chave da Lateralização no Tatame! #shorts', 33, 'short', '{controle}', '{cem_quilos}', null),
  ('hfLhraVjF8Q', 'Jiu-Jitsu: Aprenda Chave de Braço e Panturrilha (Fácil!) #shorts', 75, 'short', '{finalizacao}', '{}', null),
  ('mh5_izElvIk', 'Deashi Harai: Domine a Técnica do ''Bate Ashi'' no Judô! #shorts', 111, 'short', '{queda}', '{perna}', null),
  ('Xwyhyr8MGGo', 'BJJ: A análise da posição das pernas e controle da cabeça! #shorts', 17, 'short', '{controle}', '{}', null),
  ('W2oEz7atJN4', 'Mentalidade de Lutador: Segredos do Treino e Foco #shorts', 82, 'short', '{logica,competicao}', '{}', null),
  ('F7-KeY2WPvg', 'Garouden: Lutas Realistas e Estilos Diversos que Você Precisa Ver! #shorts', 43, 'short', '{competicao}', '{}', null),
  ('ldii79iSNbY', 'Jiu-Jitsu: Segredo da gangorra, como dominar a técnica! #shorts', 76, 'short', '{logica}', '{}', null),
  ('kdCvFv6g1V8', 'Saída de Quadril: Dicas Essenciais para Melhorar! #shorts', 82, 'short', '{fisico}', '{}', null),
  ('750lt_L6lxc', 'Técnicas de Luta: Pressão, Joelho e Finalização Perfeita! #shorts', 44, 'short', '{finalizacao,controle,competicao}', '{}', null),
  ('Lw2fqOSWBMo', 'Judô: Aprenda o Deashi Harai e o Poder do ''Ashi'' #shorts', 24, 'short', '{queda}', '{perna}', null),
  ('gytm3w3EMo8', 'Jiu-Jitsu: Estratégia Incrível da Meia Guarda Para Dominar o Combate! #shorts', 17, 'short', '{logica,guarda}', '{meia_guarda}', null),
  ('AzOCHPJGlWI', 'Lutador Abandona Lutas Após Trauma: A História Chocante! #shorts', 37, 'short', '{competicao}', '{}', null),
  ('3J4ljsA09Z0', 'Fuga de Quadril no Jiu-Jitsu: Dicas e Técnicas Essenciais! #shorts', 79, 'short', '{defesa,fisico}', '{}', null),
  ('BvoMFZpGYGk', 'Jiu-Jitsu: Técnicas de Guarda, Raspagem e Finalização! #shorts', 29, 'short', '{finalizacao,raspagem,guarda}', '{}', null),
  ('_1BpoRNztrI', 'Chave de Panturrilha: Finalização Rápida em Jiu-Jitsu #shorts', 20, 'short', '{finalizacao}', '{}', null),
  ('5kGAOLstrpg', 'Domine Movimentos: Braço e Perna em Ação! #shorts', 16, 'short', '{geral}', '{}', null),
  ('_YhXDeR-10M', 'Jiu-Jitsu: Aumente Seu Jogo! Dicas de Meia Guarda e Passagem! #shorts', 22, 'short', '{passagem,guarda}', '{meia_guarda}', null),
  ('Taez9715INw', 'Garouden na Netflix: Desvende as Técnicas de Jiu-Jitsu! #shorts', 99, 'short', '{geral}', '{}', null),
  ('rJBUJ5tINQ4', 'Jiu-Jitsu: A Técnica Secreta da Saída de Quadril Perfeita! #shorts', 62, 'short', '{fisico}', '{}', null),
  ('-0ryn7V-HQc', 'Guarda Diamante: Defesa Imbatível no Jiu-Jitsu! #shorts', 27, 'short', '{defesa,guarda}', '{}', null),
  ('0dsmG6rlUcU', 'Jiu-Jitsu: Chave de Panturrilha e Raspagem Detalhada #shorts', 50, 'short', '{finalizacao,raspagem}', '{}', null),
  ('IMqJYNXdpuc', 'Como Praticar Movimentos Iniciais: Técnica e Precisão! #shorts', 22, 'short', '{geral}', '{}', null),
  ('Gq6lLOzTr48', 'Derrotei no Jiu-Jitsu! Veja o erro que me derrubou! 🏆 #shorts', 24, 'short', '{queda}', '{}', null),
  ('Ey1oE0bwWHA', 'Garouden e Samurai de Olho Azul: Animes de Luta que Viciam! #shorts', 38, 'short', '{competicao}', '{}', null),
  ('dapGi8OiOE8', 'Fuga de Quadril: Detalhe Simples para Sair dos 100kg! #shorts', 105, 'short', '{defesa,controle,fisico}', '{cem_quilos}', null),
  ('VA6WapkISDY', 'Jiu-Jitsu: Reposição de Guarda e Domínio Estratégico #shorts', 32, 'short', '{guarda}', '{}', null),
  ('5mN0PPYU384', 'Jiu-Jitsu: Raspagem e Chave de Panturrilha Reveladas! #shorts', 71, 'short', '{finalizacao,raspagem}', '{}', null),
  ('sZLgV8zYhHM', 'Desafio da Sincronia: Tentando Acertar o Tempo! #shorts', 21, 'short', '{drill}', '{}', null),
  ('8ko_rrheres', 'Jiu-Jitsu: Entenda as Regras da Luta e os Ataques Proibidos! #shorts', 37, 'short', '{logica,competicao}', '{}', null),
  ('oJlItvYCBzw', 'Anime Rage Control: Não dê Spoiler e Veja Essa Luta Incrível! #shorts', 45, 'short', '{competicao}', '{}', null),
  ('6h4nZ9sgL18', 'Emagrecimento: Dica Simples Para Sair dos 100kg! #shorts', 26, 'short', '{defesa,controle}', '{cem_quilos}', null),
  ('oH7ScTINcjE', 'Jiu-Jitsu: Estratégia Rápida Contra Ataques na Gola! #shorts', 39, 'short', '{logica,finalizacao}', '{}', null),
  ('s38CkWzt1lc', 'Jiu-Jitsu: Técnica de Queda e Desequilíbrio do Oponente! #shorts', 30, 'short', '{queda,fisico}', '{em_pe}', null),
  ('aA_qYGo2amY', 'Jiu-Jitsu: Domine a Guarda Aberta e Supere Seus Oponentes! #shorts', 32, 'short', '{guarda}', '{guarda_aberta}', null),
  ('MkoVGesFE-k', 'Jiu-Jitsu: Escapando do Amasso! Defesa e Técnicas Essenciais #shorts', 151, 'short', '{defesa}', '{}', null),
  ('w4szYcT2pdQ', 'Movimentos Estratégicos: Domine o Tempo da Pisada! #shorts', 24, 'short', '{drill}', '{}', null),
  ('fVBo5BMSa0c', 'Jiu-Jitsu: Domine a Guarda Fechada e Supere seus Oponentes! #shorts', 35, 'short', '{guarda}', '{guarda_fechada}', null),
  ('0H7EWPLqA3g', 'Como Evitar Ser Dominado: Estratégias de Defesa Eficazes #shorts', 64, 'short', '{logica,defesa}', '{}', null),
  ('qsM54dlbiyw', 'Jiu-Jitsu: Domínio da Faixa Branca com Técnicas de Sumô! #shorts', 47, 'short', '{competicao}', '{}', 'branca'),
  ('RjJ8iuGC2Wc', 'Estratégias de Postura: Desequilibrando o Adversário! #shorts', 40, 'short', '{logica,queda}', '{}', null),
  ('qcTdPXaJbNc', 'Jiu-Jitsu: Análise e Emoção do Combate - 100 Kilos em Ação! #shorts', 30, 'short', '{geral}', '{}', null),
  ('c_gwxTcZYIc', 'Evite o ''Amasso'': Defesa Pessoal no Chão Passo a Passo #shorts', 74, 'short', '{defesa}', '{}', null),
  ('OZuMznsD04Y', 'Jiu-Jitsu: A Base ! #shorts', 45, 'short', '{geral}', '{}', null),
  ('etJfm1D9QV8', 'Flexibilidade vs Peso: Minha Experiência e Dicas! #shorts', 30, 'short', '{fisico}', '{}', null),
  ('ZBvb2rd84sI', 'Jiu-Jitsu Match: Missed Opportunity! What Went Wrong? #shorts', 31, 'short', '{geral}', '{}', null),
  ('sf-lEX8fyBg', 'Alinhamento Postural: Segredos para Equilíbrio e Firmeza #shorts', 79, 'short', '{fisico}', '{}', null),
  ('dpaaSQlP69A', 'Jiu-Jitsu: Como o Biotipo Define Seu Jogo (Dicas) #shorts', 33, 'short', '{geral}', '{}', null),
  ('c1XET_oOdaQ', 'BJJ: Análise do Guard e Dicas para Vencer Competições #shorts', 50, 'short', '{competicao}', '{}', null),
  ('adT6wzziGqw', 'Análise Tática: Movimentos e Estratégias em Campo #shorts', 21, 'short', '{logica}', '{}', null),
  ('1nbvOJWycW0', 'Queda de Perna: Domine a Técnica e Supere seus Oponentes #shorts', 47, 'short', '{queda}', '{em_pe}', null),
  ('PgPzstslFmU', 'Análise BJJ: Erros Cruciais na Guarda! Veja Agora! #shorts', 113, 'short', '{guarda}', '{}', null),
  ('XTWW1TSxBt8', 'Jiu-Jitsu: o Desequilíbrio! #shorts', 20, 'short', '{queda,fisico}', '{}', null),
  ('E0pkF4AFVhM', 'Sumô: A Técnica Secreta Revelada pelo Aluno (Incrível!) #shorts', 73, 'short', '{geral}', '{}', null),
  ('rRJvduG-1pE', 'Copa Pódio: Análise da Minha Luta no Absoluto! #shorts', 14, 'short', '{competicao}', '{}', null),
  ('JxpkdftyfSE', 'Meia Guarda: Domine a Estratégia e Vença no Jiu-Jitsu! #shorts', 107, 'short', '{logica,guarda}', '{meia_guarda}', null),
  ('RZXVAYsOCWw', 'Técnicas de Desequilíbrio: Aprimore seu Jiu-Jitsu! #shorts', 16, 'short', '{queda,fisico}', '{}', null),
  ('kUCnBbf4ArU', 'Desequilíbrio: A Técnica Secreta do Sumô que Funciona! #shorts', 149, 'short', '{queda,fisico}', '{}', null),
  ('zyfCWRdM4J0', 'Análise Tática: Como o Biotipo Influencia na Luta #shorts', 36, 'short', '{competicao}', '{}', null),
  ('vWbzT-MmjqM', 'Jiu-Jitsu: A Técnica Secreta para Vencer, Hip vs. Costas! #shorts', 38, 'short', '{controle}', '{costas}', null),
  ('X4WjrzeB2SU', 'Jiu-Jitsu: Aprenda a Desequilibrar na Guarda Agora! #shorts', 72, 'short', '{queda,guarda}', '{}', null),
  ('yqIYavSrt7k', 'Pegada Cruzada: A Análise da Técnica e Postura Perfeita! #shorts', 14, 'short', '{controle}', '{}', null),
  ('MoNQtXHXDPo', 'Domine a Meia Guarda no Jiu-Jitsu: Dicas Incríveis para Vencer! #shorts', 38, 'short', '{guarda}', '{meia_guarda}', null),
  ('AAUmiW6HovM', 'Jiu-Jitsu: Desequilibrando na Guarda Aberta (Técnicas) #shorts', 37, 'short', '{queda,guarda}', '{guarda_aberta}', null),
  ('YXo7E-qcgX8', 'Aluno Incrível: Técnica de Desequilíbrio Impressiona! #shorts', 26, 'short', '{queda,fisico}', '{}', null),
  ('GPE46XH6S9Q', 'Jiu-Jitsu: Pegadas e Giros para Desequilibrar seu Oponente #shorts', 21, 'short', '{queda,controle}', '{}', null),
  ('UrsZNXuS2s8', 'Americana Perfeita: A Técnica de Jiu-Jitsu Que Você Precisa Saber! #shorts', 26, 'short', '{finalizacao}', '{}', null),
  ('bEWaGzb2fB4', 'Aprenda Jiu-Jitsu: Técnicas Finais e Domine a Arte da Luta! #shorts', 43, 'short', '{competicao}', '{}', null),
  ('giR-zFhQRRA', 'Técnicas de Defesa: Domine a Pressão e Controle no Tatame! #shorts', 45, 'short', '{defesa,controle}', '{}', null),
  ('B1VdK97vEG8', 'Aprenda defesa pessoal: Derrubando o oponente com técnica! #shorts', 24, 'short', '{defesa,queda}', '{}', null),
  ('yBKu00OlcYw', 'Kata Gatame e Ezequiel: Domine Essa Técnica de Jiu-Jitsu! #shorts', 45, 'short', '{finalizacao}', '{}', null),
  ('YW88AUznRkg', 'Judô: Do Básico à Faixa Azul e Amarela - Nossa Jornada #shorts', 42, 'short', '{queda,competicao}', '{}', 'azul'),
  ('9jK5_agc6UI', 'Jiu-Jitsu: Aprenda a Desequilibrar e Vencer no Tatame! #shorts', 118, 'short', '{queda}', '{}', null),
  ('oAMD-guicQ0', 'Jiu-Jitsu: Ajuste de Pegada e Contra-Ataque para o Sucesso #shorts', 50, 'short', '{controle}', '{em_pe}', null),
  ('RWc7q5wpIt0', 'Entendendo a Si Mesmo: A Chave da Observação e Visão #shorts', 28, 'short', '{logica}', '{}', null),
  ('3dXp9xJwlFw', 'Jiu-Jitsu: Domine o Abdômen e Controle o Adversário! #shorts', 25, 'short', '{controle}', '{}', null),
  ('DatjeFt3O58', 'Jiu-Jitsu: Desequilíbrio! Domine a defesa com movimentos simples! #shorts', 40, 'short', '{defesa,queda,fisico}', '{}', null),
  ('84GMpycm-nQ', 'Jiu-Jitsu: Análise da Pontuação e Movimentos na Luta! #shorts', 20, 'short', '{competicao}', '{}', null),
  ('hPWfkSVCJnI', 'Desafio no Treino: Superando o Medo e Aprimorando a Técnica #shorts', 43, 'short', '{geral}', '{}', null),
  ('qAFVzGxsleo', 'Finalização Eficaz: Joelho no Tatame & Técnicas de Jiu-Jitsu #shorts', 41, 'short', '{finalizacao}', '{}', null),
  ('49AjDorBvLo', 'Domine a Flexibilidade do Punho: Segredo de Mestre em Artes Marciais! #shorts', 30, 'short', '{fisico}', '{}', null),
  ('OYGviPvJSFY', 'Jiu-Jitsu: Omoplata  #shorts', 24, 'short', '{finalizacao}', '{}', null),
  ('sZ4C1mbQREI', 'Judô: Katá vs. Competição e a Confiança Essencial #shorts', 46, 'short', '{queda,competicao}', '{}', null),
  ('lxtvo73XP98', 'Jiu-Jitsu: Técnica Avançada de Finalização No-Gi! #shorts', 31, 'short', '{finalizacao}', '{}', null),
  ('0DgNenvd2vM', 'Jiu-Jitsu: Domine o Equilíbrio e a Força do Adversário! #shorts', 40, 'short', '{fisico}', '{}', null),
  ('QvtsIFHkNLI', 'Omoplata Jiu-Jitsu: Aprenda a Escapar e Vencer! #shorts', 106, 'short', '{finalizacao,defesa}', '{}', null),
  ('-k9RXB3YQOQ', 'Aikido: Desafio de Ataque e Técnicas Sem Olhar para Baixo! #shorts', 29, 'short', '{geral}', '{}', null),
  ('cZxSnNR1DqU', 'Técnica de Jiu-Jitsu: Domine a Perna e Evite a Omoplata #shorts', 40, 'short', '{finalizacao}', '{}', null),
  ('i1PvrY20njs', 'Jiu-Jitsu: Domine a Pegada e Desequilibre Seus Oponentes! #shorts', 49, 'short', '{queda,controle}', '{}', null),
  ('BzO6Y_N5H2A', 'Estratégias de Luta: Estrangulamento e Kata Gatame Revelados! #shorts', 72, 'short', '{logica,finalizacao,competicao}', '{}', null),
  ('CyDDiNRcASM', 'Judô: Construindo Confiança e Técnicas sem Olhar! #shorts', 150, 'short', '{queda}', '{}', null),
  ('hsoBJx5TI0M', 'Escapando do Arm-Lock: Técnica Rápida e Eficaz! #shorts', 22, 'short', '{geral}', '{}', null),
  ('Dc_r8Q24Whs', 'Jiu-Jitsu: Domine a Cabeça e Quadril para Movimentos Incríveis! #shorts', 39, 'short', '{fisico}', '{}', null),
  ('OnDaTMbwXD4', 'Técnicas de Postura e Controle: A Chave Sob Pressão #shorts', 37, 'short', '{controle}', '{}', null),
  ('MdT7BQTKI3Q', 'Jiu-Jitsu: Desequilibrando o Oponente, Aprenda a Técnica Agora! #shorts', 41, 'short', '{queda}', '{}', null),
  ('NRDSqLM6z8c', 'Jiu-Jitsu: Domine o Adversário e Controle a Cabeça! #shorts', 32, 'short', '{controle}', '{}', null),
  ('V3ObG8HFR9M', 'Jiu-Jitsu: Como Controlar o Braço e Dominar a Posição #shorts', 86, 'short', '{logica,controle}', '{}', null),
  ('LWoU4PgFtwA', 'Copa Pódio: Análise da Luta no Absoluto! #shorts', 111, 'short', '{competicao}', '{}', null),
  ('7zG-tqpYs34', 'Defesa Pessoal: Técnicas Secretas de Movimentação e Controle #shorts', 34, 'short', '{defesa,controle,drill}', '{}', null),
  ('l3wUhc1brYI', 'Omoplata: Domine o Braço e Finalize com Perfeição! #shorts', 157, 'short', '{finalizacao}', '{}', null),
  ('zB6jVKRIOBc', 'Jiu-Jitsu: Análise da Posição! #shorts', 20, 'short', '{geral}', '{}', null),
  ('pBpz7sI_ETM', 'Jiu-Jitsu: Segredos do Equilíbrio e Desequilíbrio Revelados! #shorts', 44, 'short', '{queda,fisico}', '{}', null)
on conflict (id) do nothing;
