/* Planos de ataque prontos, árvore gatilho → ação → se falhar → próxima.
   Cada um traz a faixa recomendada e o aviso de legalidade IBJJF.
   Tudo editável e duplicável dentro do app. */

export const PLANOS_ATAQUE = [
  {
    slug: 'cg-trindade',
    nome: 'Trindade da Guarda Fechada',
    faixa: 'branca',
    posicao: 'Guarda fechada (por baixo)',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'O primeiro sistema de ataque que todo faixa branca precisa. Três finalizações que se alimentam: a defesa de uma abre a outra.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'ele apoia a mão no seu peito e a postura quebra', acao: 'Quebrar a postura, pegar manga + nuca', detalhe: 'Cotovelos colados, joelhos apertados. Sem quebrar postura não existe ataque.' },
      { gatilho: 'braço dele cruzou sua linha central', acao: 'Chave de braço (armlock)', seFalhar: 'ele esconde e puxa o braço de volta', detalhe: 'Angula o quadril, perna sobe pela cabeça. Joelhos fechados.' },
      { gatilho: 'ele arrancou o braço e ficou com um dentro, um fora', acao: 'Triângulo', seFalhar: 'ele posta a postura e afunda o ombro', detalhe: 'Puxa o braço através, ângulo de 90 graus antes de fechar.' },
      { gatilho: 'ele empurra o joelho e afunda contra você', acao: 'Omoplata', seFalhar: 'ele rola pra frente', proxima: 'Segurar o quadril e voltar pra guarda ou raspar', detalhe: 'Senta de lado, trava o ombro dele com a perna.' },
    ],
  },
  {
    slug: 'cg-hipbump-kimura',
    nome: 'Hip Bump → Kimura → Guilhotina',
    faixa: 'branca',
    posicao: 'Guarda fechada (por baixo)',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'O encadeamento mais simples que existe pra quem tá começando. Três reações previsíveis, três respostas prontas.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'ele senta pra trás e apoia a mão atrás do corpo', acao: 'Raspagem de gancho (hip bump)', detalhe: 'Senta junto, mão no chão, quadril bate pro lado do braço dele.' },
      { gatilho: 'ele baseia forte com a mão no chão pra não cair', acao: 'Kimura naquele braço', seFalhar: 'ele agarra o próprio cinto ou a calça', detalhe: 'Se ele defende segurando o cinto, use a perna pra quebrar a pegada.' },
      { gatilho: 'ele abaixa a cabeça pra escapar da kimura', acao: 'Guilhotina', seFalhar: 'ele levanta e postura', proxima: 'Voltar à guarda fechada e recomeçar o ciclo', detalhe: 'Braço fundo no pescoço, cotovelo colado.' },
    ],
  },
  {
    slug: 'costas-gi',
    nome: 'Ataques das Costas (Gi)',
    faixa: 'branca',
    posicao: 'Pegada nas costas',
    modo: 'gi',
    tipo: 'ataque',
    resumo: 'Costas é a melhor posição do jiu-jitsu e vale 4 pontos. Aqui é onde faixa branca mais finaliza.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'seatbelt firme + os dois ganchos', acao: 'Mata-leão', detalhe: 'Primeiro o controle, depois a finalização. Nunca solte o seatbelt pra tentar o estrangulamento.' },
      { gatilho: 'ele defende o pescoço com as duas mãos e expõe a lapela', acao: 'Estrangulamento de laço (bow and arrow)', seFalhar: 'ele defende o colarinho', detalhe: 'Pega a lapela por cima do ombro, a outra mão na calça.' },
      { gatilho: 'ele estica o braço pra defender o colarinho', acao: 'Chave de braço a partir das costas', seFalhar: 'ele recolhe o braço', proxima: 'Volta pro mata-leão, o ciclo se repete' },
    ],
  },
  {
    slug: 'costas-nogi',
    nome: 'Ataques das Costas (No-Gi)',
    faixa: 'branca',
    posicao: 'Pegada nas costas',
    modo: 'nogi',
    tipo: 'ataque',
    resumo: 'Sem lapela, o jogo das costas vira controle de mão e paciência. Body triangle segura enquanto você trabalha.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'seatbelt + ganchos ou body triangle', acao: 'Mata-leão', detalhe: 'Body triangle não pontua na IBJJF (precisa dos dois ganchos), mas controla melhor.' },
      { gatilho: 'ele defende com as duas mãos no pescoço', acao: 'Atacar a mão de baixo, quebrar a defesa', seFalhar: 'ele mantém a defesa fechada', detalhe: 'Puxa o punho dele pra baixo com as duas mãos.' },
      { gatilho: 'ele vira o corpo tentando escapar', acao: 'Triângulo invertido ou armlock', proxima: 'Se ele escapar, retomar tartaruga e recolocar ganchos' },
    ],
  },
  {
    slug: 'montada-gi',
    nome: 'Montada: Cruz na Lapela → Armlock',
    faixa: 'branca',
    posicao: 'Montada',
    modo: 'gi',
    tipo: 'ataque',
    resumo: 'Montada vale 4 pontos e é a segunda melhor posição. O truque é atacar sem perder a posição.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'montada estável, quadril baixo, lapela acessível', acao: 'Estrangulamento cruzado (cruzada)', detalhe: 'Mão fundo na lapela primeiro, depois a segunda.' },
      { gatilho: 'ele sobe os dois braços pra defender o pescoço', acao: 'Chave de braço (montada em S)', seFalhar: 'ele segura as mãos e resiste', detalhe: 'Isola o braço, sobe pra S-mount antes de deitar.' },
      { gatilho: 'ele vira de lado pra escapar', acao: 'Gift wrap → tomar as costas', proxima: 'Mata-leão ou bow and arrow' },
    ],
  },
  {
    slug: 'montada-ezequiel',
    nome: 'Encadeamento da Montada (Ezequiel)',
    faixa: 'azul',
    posicao: 'Montada',
    modo: 'gi',
    tipo: 'ataque',
    resumo: 'Ezequiel é o ataque que funciona justamente quando o cara defende bem. Você usa a defesa dele como entrada.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'ele fecha os braços protegendo o peito e o pescoço', acao: 'Ezequiel', detalhe: 'Mão por baixo da nuca, a outra puxa a manga sobre a garganta.' },
      { gatilho: 'ele empurra seu peito e estende o braço', acao: 'Armlock naquele braço', seFalhar: 'ele recolhe' },
      { gatilho: 'ele vira de lado e dá as costas', acao: 'Gift wrap → costas', proxima: 'Mata-leão' },
    ],
  },
  {
    slug: 'cemquilos-kimura',
    nome: 'Cem Quilos: Kimura → Americana → Katagatame',
    faixa: 'branca',
    posicao: '100kg (por cima)',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'Três ataques do mesmo controle. Você só muda conforme onde o braço dele está.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'braço dele longe do corpo, no chão', acao: 'Kimura', detalhe: 'Prende o pulso, passa o braço por baixo, figura 4.' },
      { gatilho: 'ele leva o braço pra baixo, colado no corpo', acao: 'Americana', seFalhar: 'ele agarra o próprio cinto/calça' },
      { gatilho: 'ele empurra sua cabeça e estende o braço pro seu pescoço', acao: 'Katagatame (braço-cabeça)', seFalhar: 'ele defende o quadril', proxima: 'Passar para norte-sul e atacar de lá' },
    ],
  },
  {
    slug: 'passagem-meia',
    nome: 'Sistema de Passagem de Meia-Guarda',
    faixa: 'azul',
    posicao: 'Meia-guarda (por cima)',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'Meia-guarda é onde a maioria dos rolas trava. Este é o caminho: matar o escudo, escolher o lado.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'você por cima, ele com knee shield', acao: 'Matar o joelho: pressionar pra baixo e ganhar cross-face', detalhe: 'Sem matar o escudo não existe passagem.' },
      { gatilho: 'escudo morto, você com underhook ou cross-face', acao: 'Passagem de joelho na barriga (knee cut)', seFalhar: 'ele recupera o underhook e senta' },
      { gatilho: 'ele bloqueia o knee cut e senta de lado', acao: 'Backstep e passar pelo outro lado', proxima: 'Estabilizar 100kg por 3s (3 pontos)' },
    ],
  },
  {
    slug: 'meia-oldschool',
    nome: 'Raspagens da Meia-Guarda',
    faixa: 'azul',
    posicao: 'Meia-guarda',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'Por baixo na meia com underhook você tem três saídas encadeadas. Sem underhook, você só sobrevive.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'você conquistou o underhook e está de lado', acao: 'Raspagem do velho (old school)', detalhe: 'Pega o tornozelo longe, cabeça pra dentro, empurra o joelho.' },
      { gatilho: 'ele bloqueia sua mão na perna', acao: 'Plano B: circular para as costas', seFalhar: 'ele vira de frente e afunda o peso' },
      { gatilho: 'ele afunda o peso pra te achatar', acao: 'Electric chair (lockdown)', proxima: 'Cai em montada ou 100kg' },
    ],
  },
  {
    slug: 'borboleta',
    nome: 'Sistema de Guarda Borboleta',
    faixa: 'azul',
    posicao: 'Guarda borboleta',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'A guarda mais direta para quem gosta de levantar e passar. Underhook manda no jogo.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'underhook + gancho ativo, ele empurrando você', acao: 'Raspagem de gancho clássica', detalhe: 'Cai pro lado do underhook, gancho eleva a perna dele.' },
      { gatilho: 'ele posta a base pro lado que você foi', acao: 'Tomar as costas', seFalhar: 'ele recua o quadril' },
      { gatilho: 'ele recua e fica de pé', acao: 'Wrestle-up (levantar em single leg)', proxima: 'Transição para X-guard' },
    ],
  },
  {
    slug: 'dlr',
    nome: 'Sistema De La Riva',
    faixa: 'roxa',
    posicao: 'De La Riva',
    modo: 'gi',
    tipo: 'ataque',
    resumo: 'Guarda de gancho externo. Vira as costas do cara com berimbolo ou raspa com tripé.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'gancho DLR firme + pega no tornozelo e lapela', acao: 'Berimbolo para as costas', detalhe: 'Inverte por baixo do quadril, não solta o tornozelo.' },
      { gatilho: 'ele resiste ao giro e joga o peso pra trás', acao: 'Raspagem de tripé / ankle pick', seFalhar: 'ele recua a perna do gancho' },
      { gatilho: 'ele recua a perna e afasta', acao: 'Transição para single leg X', proxima: 'Raspagem de single leg X' },
    ],
  },
  {
    slug: 'aranha',
    nome: 'Guarda Aranha (Gi)',
    faixa: 'azul',
    posicao: 'Guarda aranha',
    modo: 'gi',
    tipo: 'ataque',
    resumo: 'Só existe no gi. Você controla os dois braços dele e ele não consegue postar a base.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'pegadas duplas de manga + pés nos bíceps', acao: 'Raspagem de tesoura / laçada', detalhe: 'Braço esticado é braço morto. Não solte as mangas.' },
      { gatilho: 'ele baseia forte e afunda de um lado', acao: 'Triângulo', seFalhar: 'ele posta a postura e recua' },
      { gatilho: 'ele recua a postura pra escapar', acao: 'Omoplata', proxima: 'Volta pra aranha se ele rolar' },
    ],
  },
  {
    slug: 'tartaruga',
    nome: 'Tartaruga: Ataque e Defesa',
    faixa: 'azul',
    posicao: 'Tartaruga (quatro apoios)',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'Tartaruga é a posição que faixa branca mais entrega. Aprender os dois lados muda tudo.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'ele em tartaruga, você por cima', acao: 'Relógio (clock choke) no gi / colocar ganchos no no-gi', detalhe: 'Peso na omoplata dele, não nas costas.' },
      { gatilho: 'ele defende o pescoço e encolhe', acao: 'Crucifixo ou tomada de costas', seFalhar: 'ele senta de lado' },
      { gatilho: 'VOCÊ na tartaruga sendo atacado', acao: 'Granby roll ou recuperar guarda', detalhe: 'Cotovelos colados, mão no pescoço, nunca deixe entrar o gancho.' },
    ],
  },
  {
    slug: 'chave-pe-branca',
    nome: 'Chave de Pé Reta (a única legal na branca)',
    faixa: 'branca',
    posicao: 'Ashi garami',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'A única chave de perna que faixa branca pode aplicar na IBJJF. Feita errada, machuca o parceiro.',
    legal: true,
    aviso: 'LEGAL só a chave de pé RETA, das posições ashi garami reto, ashi externo e guarda 50/50. Gire SEMPRE para longe do joelho. Heel hook, toe hold, kneebar e calf slicer são ILEGAIS até marrom/preta. Knee reap é falta.',
    passos: [
      { gatilho: 'você com o pé dele preso na axila, ashi garami montado', acao: 'Chave de pé reta: quadril pra frente, girar para FORA do joelho', detalhe: 'Sem torção interna. Solta no primeiro sinal do parceiro.' },
      { gatilho: 'ele posta a mão no chão e tenta girar pra fora', acao: 'Seguir o giro e reajustar mantendo o ashi legal', proxima: 'Se perder, solta a perna e volta pra guarda aberta' },
    ],
  },
  {
    slug: 'quedas-branca',
    nome: 'Quedas Mínimas pra Faixa Branca',
    faixa: 'branca',
    posicao: 'De pé',
    modo: 'ambos',
    tipo: 'ataque',
    resumo: 'Duas quedas e uma puxada. Não precisa de mais que isso pra fechar o jogo em pé.',
    legal: true,
    aviso: 'Pular para a guarda é PROIBIDO para faixa branca na IBJJF. Sente antes de puxar.',
    passos: [
      { gatilho: 'ele com a postura alta e o peso na frente', acao: 'Baiana (double leg)', detalhe: 'Nível abaixo do dele antes de entrar. Cabeça pro lado de fora.' },
      { gatilho: 'ele defende a baiana espalhando (sprawl)', acao: 'Solo (single leg) do outro lado', seFalhar: 'ele defende de novo' },
      { gatilho: 'não conseguiu a queda e o tempo tá passando', acao: 'Sentar e puxar para a guarda (sem pular)', proxima: 'Entrar no seu sistema de guarda fechada' },
    ],
  },
  {
    slug: 'escape-defesa-branca',
    nome: 'Sobrevivência: Escapes Essenciais',
    faixa: 'branca',
    posicao: 'Sob a montada',
    modo: 'ambos',
    tipo: 'defesa',
    resumo: 'Saulo Ribeiro: sobreviver vem antes de atacar. Se você não escapa, nada mais importa.',
    legal: true,
    aviso: '',
    passos: [
      { gatilho: 'montado, braços dele de um lado', acao: 'Upa (ponte e rola)', detalhe: 'Prende o braço e a perna do mesmo lado, ponte alta pro ombro.' },
      { gatilho: 'ele baseia e a upa não sai', acao: 'Fuga de quadril (elbow escape) pra meia-guarda', seFalhar: 'ele monta de novo' },
      { gatilho: 'preso nos 100kg', acao: 'Frames de antebraço + fuga de quadril, recuperar guarda', proxima: 'Se não der, virar pra tartaruga (nunca dar as costas achatado)' },
    ],
  },
];
