/* Conteúdo editorial de Nutrição. As contas continuam em lib/nutricao.js.
   Fontes e limites revisados em 27/09/2026; não é uma prescrição individual. */
export const SUPLEMENTOS = [
  {
    id: 'creatina', nome: 'Creatina', foco: 'Força e esforços repetidos', evidencia: 'Bem estudada no esporte',
    resumo: 'Uma opção pra apoiar o treino de força e os esforços intensos que se repetem.',
    quando: 'Pra quem treina com regularidade e quer apoiar a força junto com a alimentação e o descanso.',
    tatame: 'Quedas e saídas de baixo exigem esforço curto e forte. É esse tipo de esforço que dá sentido à creatina no treino; não é garantia de ganhar o rola.',
    dose: '3 a 5 g por dia, todo dia, sem necessidade de fase de carga',
    corpo: 'A creatina aumenta a reserva de fosfocreatina do músculo, usada para repor energia em esforços intensos. Junto do treino, pode favorecer força e massa magra.',
    pratica: 'A forma mais estudada é a monohidratada. O uso diário importa mais que tomar logo antes do treino; sem carga, o aumento das reservas é gradual.',
    cuidado: 'Pode aumentar o peso pela água dentro do músculo. Se você compete por categoria, converse com quem acompanha sua pesagem.',
    limite: 'Os resultados vêm de estudos de exercício e força. Não permitem prometer mais finalizações, raciocínio mais rápido ou recuperação garantida entre rolas.',
    fontes: [{ nome: 'ISSN: creatina, 2017', url: 'https://doi.org/10.1186/s12970-017-0173-z' }],
  },
  {
    id: 'betaalanina', nome: 'Beta-alanina', foco: 'Esforço intenso sustentado', evidencia: 'Depende do tipo de esforço',
    resumo: 'Pode ajudar em esforços intensos sustentados, com uso por várias semanas.',
    quando: 'Quando o objetivo do treino envolve sustentar esforço forte. Faz sentido avaliar com o nutricionista, sem esperar efeito na primeira dose.',
    tatame: 'O rola alterna esforço e pausa. Estudos com esforço contínuo de 1 a 4 minutos não equivalem a um rola inteiro nem garantem mais resistência na pegada.',
    dose: '4 a 6 g por dia, divididos em doses de 1,6 g, por pelo menos 4 semanas',
    corpo: 'Aumenta a carnosina muscular, que ajuda a conter a acidez durante esforço intenso. Os efeitos são mais consistentes em tarefas de cerca de 1 a 4 minutos.',
    pratica: 'É o uso regular por semanas que aumenta a carnosina. Não funciona como um estímulo imediato antes de entrar no tatame.',
    cuidado: 'Pode causar formigamento. Doses menores divididas ou formulações de liberação lenta podem reduzir esse efeito.',
    limite: 'O benefício depende da tarefa. A evidência não sustenta prometer que o braço vai aguentar mais em qualquer situação de luta.',
    fontes: [{ nome: 'ISSN: beta-alanina, 2015', url: 'https://doi.org/10.1186/s12970-015-0090-y' }],
  },
  {
    id: 'cafeina', nome: 'Cafeína', foco: 'Disposição com atenção ao sono', evidencia: 'Também estudada no jiu-jitsu',
    resumo: 'Pode reduzir a percepção de esforço. O horário e a sua resposta fazem diferença.',
    quando: 'Pra avaliar em treinos em que você tolera bem a cafeína, sem sacrificar o sono depois.',
    tatame: 'Um estudo em competição simulada de jiu-jitsu encontrou melhora em ações intensas e desempenho físico. Isso não garante o mesmo resultado pra todo praticante.',
    corpo: 'Age no sistema nervoso e pode diminuir a percepção de esforço. A resposta varia entre pessoas e tarefas.',
    pratica: 'A conta do app usa 3 mg/kg. Café varia muito conforme preparo e tamanho da xícara; a equivalência é aproximada. Considere também outras fontes no dia.',
    cuidado: 'Pode causar ansiedade, palpitações e prejudicar o sono. Não existe um horário universal, como 16h, que seja seguro pro sono de todo mundo.',
    limite: 'Em um ensaio com 23 homens, 400 mg afetaram o sono mesmo 12 horas antes de dormir. É uma dose estudada, não uma recomendação. Dose e horário precisam ser considerados juntos.',
    fontes: [
      { nome: 'ISSN: cafeína, 2021', url: 'https://doi.org/10.1186/s12970-020-00383-4' },
      { nome: 'Estudo em jiu-jitsu, 2016', url: 'https://pubmed.ncbi.nlm.nih.gov/26693858/' },
      { nome: 'Dose, horário e sono, 2025', url: 'https://pubmed.ncbi.nlm.nih.gov/39377163/' },
    ],
  },
  {
    id: 'whey', nome: 'Whey', foco: 'Praticidade pra fechar a proteína', evidencia: 'Útil quando falta proteína',
    resumo: 'Uma forma prática de completar a proteína que faltou na alimentação do dia.',
    quando: 'No dia corrido em que comida sozinha não fechou sua meta. A barra de proteína do app ajuda a ver o que falta.',
    tatame: 'A proteína ajuda na reparação e adaptação muscular ao treino. Whey é uma opção prática; não garante menos dor nem substitui uma alimentação suficiente.',
    dose: 'A porção depende da proteína que falta no dia e do rótulo do produto',
    corpo: 'Fornece aminoácidos essenciais para a síntese de proteína muscular. A quantidade total do dia e a distribuição pelas refeições importam.',
    pratica: 'Confira quantos gramas de proteína há na porção, porque scoop não é uma medida igual em todas as marcas. Comida também pode fechar essa conta.',
    cuidado: 'Whey vem do leite. Alergia à proteína do leite e intolerância à lactose precisam ser consideradas na escolha.',
    limite: 'Se você já atinge sua necessidade com alimentos, adicionar whey não significa automaticamente recuperar melhor.',
    fontes: [{ nome: 'ISSN: proteína e exercício, 2017', url: 'https://doi.org/10.1186/s12970-017-0177-8' }],
  },
  {
    id: 'kefir', nome: 'Kefir e probióticos', foco: 'Intestino e tolerância individual', evidencia: 'Depende da cepa e do produto',
    resumo: 'Vale distinguir o alimento fermentado dos probióticos testados nos estudos.',
    quando: 'Kefir pode entrar como alimento, se você tolera bem. Um probiótico específico precisa ter indicação e evidência para o objetivo.',
    tatame: 'Alguns estudos em atletas apontam benefícios intestinais ou respiratórios com cepas específicas. Não dá pra prometer menos resfriados ou treinos perdidos com qualquer kefir.',
    dose: 'Não existe uma dose única de probiótico que sirva pra todo produto',
    corpo: 'Os efeitos dependem da cepa, da quantidade e do tempo de uso estudados. Dois produtos chamados probióticos podem ter resultados diferentes.',
    pratica: 'No probiótico, confira a identificação da cepa no rótulo. A composição do kefir varia e não equivale automaticamente à de um suplemento pesquisado.',
    cuidado: 'Se sintomas intestinais atrapalham o treino, procure avaliação para entender a causa e escolher a abordagem.',
    limite: 'As pesquisas em atletas ainda têm resultados variados. Kefir não deve receber uma promessa de desempenho só por ser fermentado.',
    fontes: [{ nome: 'ISSN: probióticos, 2019', url: 'https://doi.org/10.1186/s12970-019-0329-0' }],
  },
];
